Repository grpc/grpc-swift, pull requests merged in 2020-12, with the labels that each got.

#1059 Generate client service name and proto service comments
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/GRPCInteroperabilityTestModels/generate.sh
  Sources/GRPCInteroperabilityTestModels/unimplemented_call.patch
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
Labels: semver-minor ↑

#1061 Add an interceptors tutorial
  README.md
  Sources/Examples/Echo/Implementation/HPACKHeaders+Prettify.swift
  Sources/Examples/Echo/Implementation/Interceptors.swift
  Sources/Examples/Echo/README.md
  Sources/Examples/Echo/Runtime/main.swift
  Sources/Examples/HelloWorld/README.md
  Sources/Examples/README.md
  docs/interceptors-tutorial.md
Labels: semver-noop

#1060 Update cocoapods
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
Labels: semver-noop

#1064 Simplify client channel pipeline setup
  Sources/GRPC/ClientConnection.swift
Labels: semver-patch •

#1062 Pass multiplexer from ConnectionManager rather than channel
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
Labels: semver-patch •

#1071 Provide cachegrind mode.
  Sources/GRPCPerformanceTests/Benchmark.swift
Labels: semver-noop

#1068 Extract the logic from the GRPCIdleHandler into a state machine
  Package.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCIdleHandlerStateMachine.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/GRPCIdleHandlerStateMachineTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#1070 Drop support for Swift 5.0
  .swiftformat
  .travis-script.sh
  .travis.yml
  Examples/Google/NaturalLanguage/Package.swift
  Examples/PCAPExample/Package.swift
  Makefile
  Package.swift
  Performance/QPSBenchmark/Package.swift
  README.md
  Tests/GRPCTests/XCTestManifests.swift
  Tests/LinuxMain.swift
  scripts/build_podspecs.py
Labels: semver-major ⚠️

#1075 Make testClientReconnectsAutomatically less flaky
  Tests/GRPCTests/ClientConnectionBackoffTests.swift
Labels: semver-noop

#1074 Add a unary server benchmark
  .gitignore
  Sources/GRPC/_EmbeddedThroughput.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedServer.swift
  Sources/GRPCPerformanceTests/main.swift
Labels: semver-patch •

#1073 Remove a bunch of (unspecialized) generics
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
Labels: semver-patch •

#1076 Allow the server to be gracefully shutdown.
  Package.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectivityState.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCIdleHandlerStateMachine.swift
  Sources/GRPC/Server.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/GRPCIdleHandlerStateMachineTests.swift
  Tests/GRPCTests/ServerQuiescingTests.swift
  scripts/build_podspecs.py
Labels: semver-minor ↑

#1077 Make a bunch of server code inlinable
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/CallHandlerFactory.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/Interceptor/ServerInterceptorContext.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ServerInterceptors.swift
  Sources/GRPC/InterceptorContextList.swift
  Sources/GRPC/Ref.swift
  Sources/GRPC/Serialization.swift
Labels: semver-patch •

#1078 Remove dead code
  Sources/GRPC/ClientCalls/ClientCall.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientCalls/GRPCClientCallHandler.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ChannelTransportTests.swift
Labels: semver-patch •

#1079 Merge idle and keepalive handlers
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCKeepaliveHandlers.swift
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/LinuxMain.swift
Labels: semver-patch •

#1080 Simplify client transport actions and state representation
  Sources/GRPC/Interceptor/ClientTransport.swift
Labels: semver-patch •

#1082 Update pods
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
Labels: semver-noop

#1081 Make the remote address available on the server interceptor context
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCStateMachine.swift
  Sources/GRPC/Interceptor/ServerInterceptorContext.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Tests/GRPCTests/HTTP2ToRawGRPCStateMachineTests.swift
  Tests/GRPCTests/InterceptorsTests.swift
  Tests/GRPCTests/ServerInterceptorPipelineTests.swift
Labels: semver-minor ↑

#1083 Move client serialization into the transport handler
  Sources/GRPC/FakeChannel.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Sources/GRPC/Interceptor/ClientTransportFactory.swift
  Sources/GRPC/Serialization.swift
  Sources/GRPC/_GRPCClientCodecHandler.swift
  Sources/GRPCPerformanceTests/Benchmarks/UnaryThroughput.swift
  Tests/GRPCTests/ClientTransportTests.swift
Labels: semver-patch •

#1086 Add a script for diffing cachegrind output
  scripts/cg_diff.py
Labels: semver-noop
