Repository grpc/grpc-swift, pull requests merged in 2020-03, with the labels that each got.

#734 Update Swift 5.2 development build
  .travis.yml
Labels: nio, semver-patch •

#733 Configure client connections with a builder
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Tests/GRPCTests/ClientTLSTests.swift
  Tests/GRPCTests/CompressionTests.swift
Labels: enhancement, nio, semver-minor ↑

#730 Normalize user-provided headers
  Sources/GRPC/GRPCClientStateMachine.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Tests/GRPCTests/GRPCClientStateMachineTests.swift
  Tests/GRPCTests/HeaderNormalizationTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: nio, semver-patch •

#740 Avoid generating multiple conformances to GRPCProtobufPayload
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Conformance.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  Sources/protoc-gen-grpc-swift/main.swift
Labels: nio, semver-patch •

#743 Generate documentation from proto comments
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
Labels: nio, semver-patch •

#748 Replace usage of ClientConnection.init with builders
  Sources/Examples/Echo/Runtime/main.swift
  Sources/Examples/HelloWorld/Client/main.swift
  Sources/Examples/RouteGuide/Client/main.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPCConnectionBackoffInteropTest/main.swift
  Sources/GRPCInteroperabilityTests/main.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCase.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestClientConnection.swift
  Sources/GRPCPerformanceTests/Benchmarks/ServerProvidingBenchmark.swift
  Sources/GRPCPerformanceTests/Benchmarks/UnaryThroughput.swift
  Tests/GRPCTests/BasicEchoTestCase.swift
  Tests/GRPCTests/ClientConnectionBackoffTests.swift
  Tests/GRPCTests/GRPCCustomPayloadTests.swift
  Tests/GRPCTests/GRPCInteroperabilityTests.swift
  Tests/GRPCTests/HeaderNormalizationTests.swift
  docs/basic-tutorial.md
Labels: nio, semver-patch •

#749 Update README with Swift 5.2 dependency instructions
  Package.swift
  README.md
Labels: nio, semver-patch •

#750 Update CI
  .travis.yml
Labels: nio, semver-patch •

#752 Add a server builder
  Sources/Examples/Echo/Runtime/main.swift
  Sources/Examples/HelloWorld/Server/main.swift
  Sources/Examples/RouteGuide/Server/main.swift
  Sources/GRPC/ServerBuilder.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestServer.swift
  Sources/GRPCPerformanceTests/Benchmarks/ServerProvidingBenchmark.swift
  Tests/GRPCTests/BasicEchoTestCase.swift
  Tests/GRPCTests/ClientConnectionBackoffTests.swift
  Tests/GRPCTests/ClientTLSFailureTests.swift
  Tests/GRPCTests/ClientTLSTests.swift
  Tests/GRPCTests/CompressionTests.swift
  Tests/GRPCTests/GRPCCustomPayloadTests.swift
  Tests/GRPCTests/HeaderNormalizationTests.swift
  docs/basic-tutorial.md
Labels: nio, semver-minor ↑

#754 Update CI to point to master
  .travis.yml
Labels: nio, semver-patch •

#760 Added .git ending for `swift-log`
  Package.swift
Labels: nio, semver-patch •

#761 Remove required platforms from SPM
  Package.resolved
  Package.swift
  Sources/GRPC/GRPCError.swift
Labels: nio, semver-patch •

#765 Change Swift 5.2 development to release for CI
  .travis.yml
Labels: nio, semver-patch •

#769 Point build badge to master branch
  README.md
Labels: nio, semver-patch •
