Repository grpc/grpc-swift, pull requests merged in 2020-08, with the labels that each got.

#916 Don't specify a custom module name when generating Podspecs
  scripts/build_podspecs.py
Labels: cocoapods, semver-noop

#917 Mitigate zero-length writes issue.
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/PlatformSupport.swift
  Sources/GRPC/Server.swift
  Tests/GRPCTests/PlatformSupportTests.swift
  Tests/GRPCTests/XCTestManifests.swift
  Tests/GRPCTests/ZeroLengthWriteTests.swift
Labels: semver-patch •

#919 Update docs and CI to reflect our 'main' branch
  .travis.yml
  Examples/Google/SpeechToText/Sources/SpeechService.swift
  README.md
Labels: semver-noop

#920 Switch a `numericCast` to the required type
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
Labels: semver-patch •

#924 Improve performance of routing inbound RPCs
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/Server.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  Tests/GRPCTests/GRPCCustomPayloadTests.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
Labels: semver-major ⚠️

#923 Add a 'preflight check' stage to CI
  .travis-install.sh
  .travis-script.sh
  .travis.yml
  scripts/license-check.sh
  scripts/sanity.sh
Labels: semver-noop

#927 Tolerate missing content-type header for trailers-only responses
  Sources/GRPC/GRPCClientStateMachine.swift
  Tests/GRPCTests/GRPCClientStateMachineTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#931 Pre-cache the services by name dictionary.
  Sources/GRPC/Server.swift
Labels: semver-patch •

#932 Reduce cost of responding to unary calls.
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
Labels: semver-patch •

#930 Revert "Don't specify a custom module name when generating Podspecs (#916)"
  scripts/build_podspecs.py
Labels: cocoapods, semver-noop

#933 Fix a few incorrect source locations in logs
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientErrorDelegate.swift
  Tests/GRPCTests/CapturingLogHandler.swift
  Tests/GRPCTests/GRPCTestCase.swift
Labels: semver-patch •

#934 Pin the SwiftFormat version in CI
  .travis-install.sh
  scripts/sanity.sh
Labels: semver-noop

#936 Disable new swiftformat rule
  .swiftformat
  .travis-install.sh
  Tests/GRPCTests/FakeResponseStreamTests.swift
  scripts/sanity.sh
Labels: semver-patch •

#940 Update quick-start.md
  docs/quick-start.md
Labels: semver-noop

#938 Log some HTTP/2 information
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCTimeout.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Sources/GRPC/Logger.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/_GRPCClientChannelHandler.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/GRPCTestCase.swift
  Tests/GRPCTests/GRPCTimeoutTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#942 Make 'GRPCStatus.Code' an enum
  Sources/GRPC/GRPCStatus.swift
  Sources/GRPC/Shims.swift
  Tests/GRPCTests/GRPCStatusCodeTests.swift
  Tests/GRPCTests/GRPCStatusTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#944 Update the Podspecs to alpha18.
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
Labels: cocoapods, semver-noop

#945 Allow the gRPC module name to be customised when generating code
  README.md
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  Sources/protoc-gen-grpc-swift/options.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
  dev/codegen-tests/06-test-client-only/golden/test.grpc.swift
  docs/plugin.md
Labels: cocoapods, codegen, semver-patch •

#948 Fix perf benchmarks
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
  Sources/GRPCPerformanceTests/main.swift
Labels: semver-noop

#950 Tolerate idling from the active state
  Sources/GRPC/ConnectionManager.swift
  Tests/GRPCTests/GRPCKeepaliveTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#952 Import SwiftProtobuf in generated code
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
  dev/codegen-tests/06-test-client-only/golden/test.grpc.swift
Labels: semver-patch •

#953 Move idle handler state to closed on channelInactive
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCKeepaliveHandlers.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#954 Update NIO version to 2.22.0 and NIOHTTP2 to 1.14.1.
  Package.resolved
  Package.swift
  Sources/GRPC/GRPCClientStateMachine.swift
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Sources/GRPC/Serialization.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
Labels: semver-patch •

#957 Minor SwiftFormat update
  Examples/Google/SpeechToText/Sources/ViewController.swift
  Sources/GRPC/GRPCKeepaliveHandlers.swift
  Sources/GRPC/GRPCTimeout.swift
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
Labels: semver-patch •
