Repository grpc/grpc-swift, pull requests merged in 2020-07, with the labels that each got.

#867 Replace Compression option enum with a struct
  Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift
  Sources/GRPC/ClientCalls/ClientStreamingCall.swift
  Sources/GRPC/Compression/MessageEncoding.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
Labels: nio, semver-major ⚠️

#871 Remove warning from a now-redundant try
  Package.resolved
  Package.swift
  Sources/GRPC/Server.swift
Labels: nio, semver-patch •

#870 Provide the codegen with an option to generate test clients
  Makefile
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPC/FakeChannel.swift
  Sources/GRPC/GRPCClient.swift
  Sources/GRPC/Shims.swift
  Sources/GRPC/_FakeResponseStream.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator-Names.swift
  Sources/protoc-gen-grpc-swift/options.swift
  Tests/GRPCTests/EchoTestClientTests.swift
  Tests/GRPCTests/FakeChannelTests.swift
  Tests/GRPCTests/TestClientExample.swift
  Tests/GRPCTests/XCTestManifests.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
  docs/plugin.md
Labels: enhancement, nio, semver-major ⚠️

#869 Add Generation of gRPC-Swift.podspec
  CGRPCZlib.podspec
  README.md
  gRPC-Swift.podspec
  scripts/build_podspecs.py
Labels: cocoapods, nio, semver-noop

#872 Add a script to generate a bundle of plugins for CocoaPods
  scripts/bundle-plugins-for-release.sh
Labels: nio, semver-noop

#875 Avoid a double-idle in the idle handler.
  Sources/GRPC/GRPCIdleHandler.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: bug, semver-patch •

#876 Remove 'nio' tag from Issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/QUESTION.md
Labels: semver-noop

#866 Turn Network{Implementation,Preference} enums into structs
  Sources/GRPC/PlatformSupport.swift
Labels: enhancement, semver-major ⚠️

#879 Generate conformance when message are nested
  Sources/protoc-gen-grpc-swift/Generator-Conformance.swift
  dev/codegen-tests/04-messages-only/golden/test.grpc.swift
  dev/codegen-tests/04-messages-only/proto/test.proto
Labels: bug, codegen, semver-patch •

#881 Allow separate generation of test clients
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  Sources/protoc-gen-grpc-swift/options.swift
  dev/codegen-tests/06-test-client-only/generate-and-diff.sh
  dev/codegen-tests/06-test-client-only/golden/test.grpc.swift
  dev/codegen-tests/06-test-client-only/proto/test.proto
  docs/plugin.md
Labels: codegen, semver-patch •

#880 Remove GRPCStreamType public enum
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/GRPCError.swift
  Sources/GRPC/_GRPCClientChannelHandler.swift
Labels: semver-major ⚠️

#882 Fix incorrect documentation for certificate verification on the server builder
  Sources/GRPC/ServerBuilder.swift
  Sources/GRPC/TLSConfiguration.swift
Labels: documentation, semver-noop

#850 Add keepalive handlers
  Package.resolved
  Package.swift
  README.md
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionIdledEvent.swift
  Sources/GRPC/ConnectionKeepalive.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCKeepaliveHandlers.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Tests/GRPCTests/GRPCPingHandlerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
  docs/keepalive.md
Labels: enhancement, semver-minor ↑

#886 Remove the requirement that messages conform to GRPCPayload on the server
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/CallHandlerFactory.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerCodecHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Sources/GRPC/LengthPrefixedMessageWriter.swift
  Sources/GRPC/Serialization.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/Shims.swift
  Sources/GRPC/StreamEvent.swift
  Sources/GRPC/_MessageContext.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  Tests/GRPCTests/GRPCCustomPayloadTests.swift
  Tests/GRPCTests/GRPCServerCodecHandlerTests.swift
  Tests/GRPCTests/HTTP1ToGRPCServerCodecTests.swift
  Tests/GRPCTests/XCTestManifests.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
Labels: codegen, semver-major ⚠️

#888 Alter the documented requirements of `MessageSerializer`
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Sources/GRPC/LengthPrefixedMessageWriter.swift
  Sources/GRPC/Serialization.swift
  Tests/GRPCTests/LengthPrefixedMessageWriterTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#890 Reduce input size in some tests
  Tests/GRPCTests/FunctionalTests.swift
Labels: semver-noop

#893 Tolerate receiving pings when `permitWithoutCalls` is disabled
  Sources/GRPC/GRPCKeepaliveHandlers.swift
  Tests/GRPCTests/GRPCPingHandlerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#894 Add back GRPCPayload support for server handlers
  Sources/GRPC/CallHandlers/CallHandlerFactory.swift
  Tests/GRPCTests/GRPCCustomPayloadTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#896 NetworkPreference.best should be POSIX on older platforms
  Sources/GRPC/PlatformSupport.swift
Labels: semver-patch •

#902 Allow loggers to be passed in
  Package.resolved
  Package.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ClientOptions.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/FakeChannel.swift
  Sources/GRPC/GRPCChannel/EmbeddedGRPCChannel.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Sources/GRPC/Logger.swift
  Sources/GRPC/LoggingServerErrorDelegate.swift
  Sources/GRPC/PlatformSupport.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Sources/GRPC/_GRPCClientChannelHandler.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestServer.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
Labels: semver-minor ↑

#903 Capture logs in tests
  Tests/GRPCTests/AnyServiceClientTests.swift
  Tests/GRPCTests/BasicEchoTestCase.swift
  Tests/GRPCTests/CallStartBehaviorTests.swift
  Tests/GRPCTests/CapturingLogHandler.swift
  Tests/GRPCTests/ClientConnectionBackoffTests.swift
  Tests/GRPCTests/ClientTLSFailureTests.swift
  Tests/GRPCTests/ClientTLSTests.swift
  Tests/GRPCTests/ClientTimeoutTests.swift
  Tests/GRPCTests/CompressionTests.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/EchoTestClientTests.swift
  Tests/GRPCTests/FakeChannelTests.swift
  Tests/GRPCTests/GRPCCustomPayloadTests.swift
  Tests/GRPCTests/GRPCIdleTests.swift
  Tests/GRPCTests/GRPCInteroperabilityTests.swift
  Tests/GRPCTests/GRPCServerRequestRoutingHandlerTests.swift
  Tests/GRPCTests/GRPCTestCase.swift
  Tests/GRPCTests/HTTP1ToGRPCServerCodecTests.swift
  Tests/GRPCTests/HeaderNormalizationTests.swift
  Tests/GRPCTests/PlatformSupportTests.swift
  Tests/GRPCTests/ServerTLSErrorTests.swift
  Tests/GRPCTests/TestClientExample.swift
Labels: semver-noop

#905 Fix license header check
  Sources/GRPC/_EmbeddedThroughput.swift
  scripts/license-check.sh
Labels: semver-noop

#873 Continuing #762: Added trailing HTTPHeaders for custom error reporting
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCStatusAndMetadata.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/ServerErrorDelegate.swift
  Tests/GRPCTests/ServerErrorDelegateTests.swift
  Tests/GRPCTests/ServerThrowingTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#906 Remove some unnecessary CoWs
  Sources/GRPC/GRPCClientStateMachine.swift
  Sources/GRPC/LengthPrefixedMessageReader.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
  Sources/GRPCPerformanceTests/main.swift
Labels: semver-patch •

#907 Reduce code duplication between builders and configuration
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/ServerBuilder.swift
Labels: semver-patch •

#908 Add a client debugging initializer and PCAP debugging example
  Examples/PCAPExample/.gitignore
  Examples/PCAPExample/Package.swift
  Examples/PCAPExample/README.md
  Examples/PCAPExample/Sources/PCAPExample/echo.grpc.swift
  Examples/PCAPExample/Sources/PCAPExample/echo.pb.swift
  Examples/PCAPExample/Sources/PCAPExample/main.swift
  Examples/README.md
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Tests/GRPCTests/ClientDebugChannelInitializerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#910 Update QUESTION.md
  .github/ISSUE_TEMPLATE/QUESTION.md
Labels: semver-noop

#911 Add a server debug channel initializer
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Tests/GRPCTests/DebugChannelInitializerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑
