Repository grpc/grpc-swift, pull requests merged in 2020-10, with the labels that each got.

#982 Update CocoaPods to alpha.20
  CGRPCZlib.podspec
  Examples/Google/SpeechToText/Podfile
  README.md
  docs/basic-tutorial.md
  docs/quick-start.md
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
  scripts/build_podspecs.py
Labels: semver-noop

#984 Provide more specific errors messages for failing channels
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Tests/GRPCTests/ChannelTransportTests.swift
  Tests/GRPCTests/ConnectionFailingTests.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#986 Add scaffolding for client interceptors
  Sources/GRPC/Array+BoundsCheck.swift
  Sources/GRPC/Interceptor/ClientInterceptor.swift
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientParts.swift
  Tests/GRPCTests/Array+BoundsCheckingTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#989 Make 'GRPCStatus' a struct
  Sources/GRPC/GRPCStatus.swift
Labels: semver-patch •

#993 Add head and tail interceptors.
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientInterceptorProtocol.swift
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/ClientParts.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#995 Pin formatter
  .gitignore
  .travis-install.sh
  scripts/format.sh
Labels: semver-noop

#990 Basic Async Unary implementation of QPS benchmark
  Performance/QPSBenchmark/.gitignore
  Performance/QPSBenchmark/Makefile
  Performance/QPSBenchmark/Package.swift
  Performance/QPSBenchmark/README.md
  Performance/QPSBenchmark/Sources/BenchmarkUtils/Histogram.swift
  Performance/QPSBenchmark/Sources/BenchmarkUtils/StatusCounts.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.grpc.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/control.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/control.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/core_stats.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/core_stats.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/messages.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/messages.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/payloads.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/payloads.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/stats.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/stats.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.grpc.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncClient.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncServer.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/BenchmarkServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ClientInterface.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ClientUtilities.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/HistogramSerialisation.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/QPSWorker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ResourceUsage.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ServerInterface.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ServerTypeExtensions.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ServerUtilities.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Stats.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/StatusCountsSerialisation.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/WorkerServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/grpcTime.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/main.swift
  Performance/QPSBenchmark/Tests/BenchmarkUtilsTests/HistogramTests.swift
  Performance/QPSBenchmark/Tests/BenchmarkUtilsTests/StatusCountsTests.swift
Labels: semver-noop

#1001 Add a client transport
  Package.resolved
  Sources/GRPC/ClientCalls/CallDetails.swift
  Sources/GRPC/GRPCError.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ClientTransportTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#1002 Provide a "call" object for clients
  Sources/GRPC/ClientCalls/Call.swift
  Sources/GRPC/ClientCalls/CallDetails.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/FakeChannel.swift
  Sources/GRPC/GRPCChannel/EmbeddedGRPCChannel.swift
  Sources/GRPC/GRPCChannel/GRPCChannel.swift
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Sources/GRPC/Interceptor/ClientTransportFactory.swift
  Tests/GRPCTests/ClientCallTests.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/ClientTransportTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#998 Add support for watchOS to the podspecs
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
  scripts/build_podspecs.py
Labels: semver-noop

#1004 Add an Async Ping Pong streaming benchmark
  Performance/QPSBenchmark/README.md
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncClient.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncPingPongRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncUnaryRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/RequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Stats.swift
Labels: semver-noop

#1009 Make the description of 'RPCTimedOut' static
  Sources/GRPC/GRPCError.swift
Labels: semver-patch •

#1008 Stop checking in Package.resolved
  .gitignore
  Makefile
  Package.resolved
Labels: semver-noop

#1006 Add interceptor pipeline timeouts
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#1013 Remove duplicated code.
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
Labels: semver-patch •

#1016 Tolerate identity compression as no compression
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Tests/GRPCTests/CompressionTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#1017 Remove HTTP1 types from the public server API
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerCodecHandler.swift
  Sources/GRPC/GRPCStatusAndMetadata.swift
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/ServerErrorDelegate.swift
  Sources/GRPC/Shims.swift
  Sources/GRPCInteroperabilityTestsImplementation/GRPCTestingConvenienceMethods.swift
  Sources/GRPCInteroperabilityTestsImplementation/TestServiceProvider.swift
  Tests/GRPCTests/HTTP1ToGRPCServerCodecTests.swift
  Tests/GRPCTests/HeaderNormalizationTests.swift
  Tests/GRPCTests/ServerErrorDelegateTests.swift
  Tests/GRPCTests/ServerThrowingTests.swift
Labels: semver-major ⚠️

#1010 Wire up the Call objects
  Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift
  Sources/GRPC/ClientCalls/Call.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientCalls/ClientStreamingCall.swift
  Sources/GRPC/ClientCalls/ResponseContainers.swift
  Sources/GRPC/ClientCalls/ServerStreamingCall.swift
  Sources/GRPC/ClientCalls/UnaryCall.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/FakeChannel.swift
  Sources/GRPC/GRPCChannel/EmbeddedGRPCChannel.swift
  Sources/GRPC/GRPCChannel/GRPCChannel.swift
  Sources/GRPC/GRPCClient.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ClientTransportTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-minor ↑

#1018 Tidy up some of the logic in the server call contexts
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
Labels: semver-patch •

#1021 Fix typo protoc plugin name in README
  README.md
Labels: semver-noop

#1019 Rename the client interceptor methods
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientInterceptorProtocol.swift
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
Labels: semver-patch •

#1020 Allow responses to be sent without a promise
  Performance/QPSBenchmark/README.md
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/BenchmarkServiceImpl.swift
  Performance/QPSBenchmark/scenarios/bidirectional-ping-pong.json
  Performance/QPSBenchmark/scenarios/unary-unconstrained.json
  Sources/Examples/Echo/Implementation/EchoProvider.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
Labels: semver-minor ↑

#1011 Reduce excessive server logging.
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
Labels: semver-patch •

#1012 Clarify logging from client
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncClient.swift
Labels: semver-noop

#1024 Scaffolding for server interceptors
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/ClientParts.swift
  Sources/GRPC/Interceptor/MessageParts.swift
  Sources/GRPC/Interceptor/ServerInterceptorContext.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ServerInterceptors.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/InterceptorsTests.swift
Labels: semver-minor ↑
