Repository grpc/grpc-swift, pull requests merged in 2020-11, with the labels that each got.

#1028 Restructure `_BaseCallHandler` et al. for interceptors
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/CallHandlerFactory.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCError.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ServerInterceptors.swift
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/Shims.swift
  Sources/GRPC/_GRPCClientChannelHandler.swift
  Tests/GRPCTests/ServerErrorDelegateTests.swift
  Tests/GRPCTests/ServerInterceptorPipelineTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#1030 Codegen for server interceptors
  Sources/Examples/Echo/Implementation/EchoProvider.swift
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/HelloWorld/Server/GreeterProvider.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/Examples/RouteGuide/Server/RouteGuideProvider.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/GRPCInteroperabilityTestsImplementation/TestServiceProvider.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator-Names.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  Tests/GRPCTests/HeaderNormalizationTests.swift
  Tests/GRPCTests/ImmediateServerFailureTests.swift
  Tests/GRPCTests/InterceptorsTests.swift
  Tests/GRPCTests/ServerInterceptorPipelineTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
  Tests/GRPCTests/ServerThrowingTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
Labels: semver-minor ↑

#1033 Use the server hostname override as the :authority, if present
  Sources/GRPC/ClientConnection.swift
  Tests/GRPCTests/ClientTLSTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#1032 Prefix '{Client,Server}{Request,Response}Part' with 'GRPC'
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/ClientCalls/Call.swift
  Sources/GRPC/ClientCalls/ResponseContainers.swift
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientInterceptorProtocol.swift
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Sources/GRPC/Interceptor/ClientTransportFactory.swift
  Sources/GRPC/Interceptor/MessageParts.swift
  Sources/GRPC/Interceptor/ServerInterceptorContext.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ServerInterceptors.swift
  Tests/GRPCTests/ClientCallTests.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/ClientTransportTests.swift
  Tests/GRPCTests/InterceptorsTests.swift
  Tests/GRPCTests/ServerInterceptorPipelineTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-patch •

#1031 Add a 'UserInfo' heterotyped dictionary
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/Interceptor/ServerInterceptorContext.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/Ref.swift
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/UserInfo.swift
  Tests/GRPCTests/InterceptorsTests.swift
  Tests/GRPCTests/ServerInterceptorPipelineTests.swift
  Tests/GRPCTests/UserInfoTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#1027 Split path strings using UTF8
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Tests/GRPCTests/GRPCServerRequestRoutingHandlerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-patch •

#1037 Fix incompatible code between main and the interceptors feature branch
  Tests/GRPCTests/ClientTLSTests.swift
Labels: semver-noop

#1039 Avoid allocations when accessing interceptor head/tail
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/InterceptorContextList.swift
Labels: semver-patch •

#1043 Get QPS Benchmark to run on Linux
  Performance/QPSBenchmark/README.md
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ResourceUsage.swift
Labels: semver-noop

#1045 Add single connection performance scenarios
  Performance/QPSBenchmark/README.md
  Performance/QPSBenchmark/scenarios/bidirectional-ping-pong-1-connection.json
  Performance/QPSBenchmark/scenarios/unary-1-connection.json
Labels: semver-noop

#1046 Move server (de)serialization to the base call handler
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/CallHandlerFactory.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerCodecHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/Serialization.swift
  Tests/GRPCTests/GRPCServerCodecHandlerTests.swift
  Tests/GRPCTests/GRPCServerRequestRoutingHandlerTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#1048 Add an HTTP/2 to raw gRPC server codec
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
Labels: semver-minor ↑

#1047 Add a gRPC Web to HTTP/2 codec
  Sources/GRPC/GRPCWebToHTTP2ServerCodec.swift
  Tests/GRPCTests/GRPCWebToHTTP2ServerCodecTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#1050 Plug in and switch on the 'HTTP/2 first' server handlers
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/HTTP1ToGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCStateMachine.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Sources/GRPC/MessageEncodingHeaderValidator.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Tests/GRPCTests/CallPathTests.swift
  Tests/GRPCTests/ClientTLSTests.swift
  Tests/GRPCTests/GRPCServerRequestRoutingHandlerTests.swift
  Tests/GRPCTests/HTTP1ToGRPCServerCodecTests.swift
  Tests/GRPCTests/ServerErrorDelegateTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
  Tests/GRPCTests/ServerThrowingTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-major ⚠️

#1052 Fix typo in 'requestDeserializer'
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
Labels: semver-patch •

#1054 Ensure we're on the event loop when sending streaming responses
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
Labels: semver-patch •

#1055 Use ALPN to determine what sort of connection we've accepted
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Sources/GRPC/TLSConfiguration.swift
  Sources/GRPC/TLSVerificationHandler.swift
  Tests/GRPCTests/GRPCServerPipelineConfiguratorTests.swift
  Tests/GRPCTests/HTTPVersionParserTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: semver-minor ↑

#1058 Only generate services described in files in the codegen request
  Sources/protoc-gen-grpc-swift/main.swift
Labels: semver-patch •
