Repository grpc/grpc-swift, pull requests merged in 2020-06, with the labels that each got.

#818 Add a server-idle handler
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
Labels: nio, semver-patch •

#825 Revert #782 and suppress warnings
  Tests/GRPCTests/EventLoopFuture+Assertions.swift
  Tests/GRPCTests/MagicFile.swift
  Tests/GRPCTests/SampleCertificate+Assertions.swift
Labels: semver-patch •

#824 Make idle timeout configurable
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/HTTPProtocolSwitcher.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Tests/GRPCTests/GRPCIdleTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: nio, semver-major ⚠️

#833 Ignore additional state changes after expecations have been met
  Tests/GRPCTests/ConnectionManagerTests.swift
Labels: semver-patch •

#832 Update CI
  .travis.yml
Labels: semver-patch •

#839 Turn the RequestIDProvider enum into a struct
  Sources/GRPC/ClientOptions.swift
  Tests/GRPCTests/RequestIDProviderTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: nio, semver-major ⚠️

#840 Add 'isOk' to GRPCStatus
  Sources/GRPC/GRPCStatus.swift
Labels: nio, semver-minor ↑

#841 Make language more inclusive
  Sources/GRPCPerformanceTests/main.swift
Labels: nio, semver-patch •

#834 Provide an internal transport abstraction for client rpcs
  Sources/GRPC/ClientCalls/BaseClientCall.swift
  Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift
  Sources/GRPC/ClientCalls/ClientCall.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientCalls/ClientStreamingCall.swift
  Sources/GRPC/ClientCalls/GRPCClientCallHandler.swift
  Sources/GRPC/ClientCalls/LazyEventLoopPromise.swift
  Sources/GRPC/ClientCalls/ResponsePartContainer.swift
  Sources/GRPC/ClientCalls/ServerStreamingCall.swift
  Sources/GRPC/ClientCalls/UnaryCall.swift
  Sources/GRPC/GRPCClientResponseChannelHandler.swift
  Sources/GRPC/_ClientRequestChannelHandler.swift
  Sources/GRPC/_GRPCClientChannelHandler.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCases.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
  Tests/GRPCTests/ChannelTransportTests.swift
  Tests/GRPCTests/ClientClosedChannelTests.swift
  Tests/GRPCTests/FunctionalTests.swift
  Tests/GRPCTests/GRPCStatusCodeTests.swift
  Tests/GRPCTests/LazyEventLoopPromiseTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: nio, semver-major ⚠️

#842 Allow deadlines or timeouts to be set on RPCs
  Sources/Examples/RouteGuide/Client/main.swift
  Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientCalls/ClientStreamingCall.swift
  Sources/GRPC/ClientCalls/ServerStreamingCall.swift
  Sources/GRPC/ClientCalls/UnaryCall.swift
  Sources/GRPC/ClientOptions.swift
  Sources/GRPC/GRPCClientStateMachine.swift
  Sources/GRPC/GRPCError.swift
  Sources/GRPC/GRPCTimeout.swift
  Sources/GRPC/Shims.swift
  Sources/GRPC/TimeLimit.swift
  Sources/GRPC/_GRPCClientChannelHandler.swift
  Sources/GRPCConnectionBackoffInteropTest/main.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCases.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
  Tests/GRPCTests/ChannelTransportTests.swift
  Tests/GRPCTests/ClientTimeoutTests.swift
  Tests/GRPCTests/FunctionalTests.swift
  Tests/GRPCTests/GRPCClientStateMachineTests.swift
  Tests/GRPCTests/GRPCStatusCodeTests.swift
  Tests/GRPCTests/GRPCTimeoutTests.swift
  Tests/GRPCTests/TimeLimitTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: nio, semver-major ⚠️

#845 Add default user-agent to header if customMetadata doesn't have one
  Sources/GRPC/GRPCClientStateMachine.swift
  Tests/GRPCTests/GRPCClientStateMachineTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: enhancement, nio, semver-patch •

#847 Avoid race condition when scheduling a timeout
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
Labels: bug, nio, semver-patch •

#851 fix Examples/Google pod install failed
  Examples/Google/SpeechToText/Podfile
  Examples/Google/SpeechToText/Podfile.lock
Labels: nio, semver-patch •

#849 Allow the connectivity state delegate queue to be specified
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectivityState.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Tests/GRPCTests/ConnectivityStateMonitorTests.swift
Labels: enhancement, nio, semver-minor ↑

#848 Stop sending requests in call init
  Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift
  Sources/GRPC/ClientCalls/ClientStreamingCall.swift
  Sources/GRPC/ClientCalls/ServerStreamingCall.swift
  Sources/GRPC/ClientCalls/UnaryCall.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/GRPCChannel/EmbeddedGRPCChannel.swift
Labels: nio, semver-patch •

#856 Refactor some of the client code generation
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.pb.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
Labels: nio, semver-patch •

#858 Update license check and generated code
  Makefile
  Sources/Examples/Echo/Model/echo.pb.swift
  Sources/Examples/RouteGuide/Model/route_guide.pb.swift
  Sources/GRPCInteroperabilityTestModels/Generated/empty.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/empty.pb.swift
  Sources/GRPCInteroperabilityTestModels/Generated/messages.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/messages.pb.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.pb.swift
  scripts/license-check.sh
Labels: nio, semver-patch •

#859 Provide errors to failed client promises rather than a status
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientCalls/ResponsePartContainer.swift
  Tests/GRPCTests/ChannelTransportTests.swift
  Tests/GRPCTests/ClientCancellingTests.swift
  Tests/GRPCTests/ClientTimeoutTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: nio, semver-minor ↑

#861 Replace 'ConnectionTarget' enum with a struct
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/Server.swift
Labels: nio, semver-major ⚠️

#855 Provide 'fake' responses for generated test clients
  Sources/GRPC/_FakeResponseStream.swift
  Tests/GRPCTests/FakeResponseStreamTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: enhancement, nio, semver-minor ↑

#860 Allow users to choose a policy for starting RPCs
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Tests/GRPCTests/CallStartBehaviorTests.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: enhancement, nio, semver-minor ↑

#864 Provide a 'FakeChannel'
  Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift
  Sources/GRPC/ClientCalls/ClientCallTransport.swift
  Sources/GRPC/ClientCalls/ClientStreamingCall.swift
  Sources/GRPC/ClientCalls/ServerStreamingCall.swift
  Sources/GRPC/ClientCalls/UnaryCall.swift
  Sources/GRPC/FakeChannel.swift
  Sources/GRPC/WriteCapturingHandler.swift
  Sources/GRPC/_FakeResponseStream.swift
  Tests/GRPCTests/FakeChannelTests.swift
  Tests/GRPCTests/XCTestManifests.swift
Labels: enhancement, nio, semver-minor ↑

#865 Require generated client protocols to accept `CallOptions`
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
Labels: codegen, nio, semver-major ⚠️
