Repository grpc/grpc-swift, pull requests merged in 2021-07, with the labels that each got.

#1209 Fix creating the client link
  docs/basic-tutorial.md
Labels: semver-noop

#1211 Bump the minimum version of argument parser
  Package.swift
Labels: semver-patch •

#1212 Bump version to 1.1.1
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1214 Migrate from travis.org to GitHub actions.
  .github/workflows/ci.yaml
  .travis-install.sh
  .travis-script.sh
  .travis.yml
Labels: semver-noop

#1216 Comment out testBidirectionalStreamingOnCloseAfterUserFunctionFails
  Tests/GRPCTests/ServerOnCloseTests.swift
Labels: semver-noop

#1218 Use new NIOSSL API for making 'TLSConfiguration'
  Package.swift
  Sources/GRPC/TLSConfiguration.swift
  Tests/GRPCTests/ALPNConfigurationTests.swift
Labels: semver-patch •

#1213 Check Swift reserved names when generating function names
  Sources/protoc-gen-grpc-swift/Generator-Names.swift
Labels: semver-patch •

#1219 Bump version number
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1221 Add support for Network.framework TLS options
  Sources/Examples/Echo/Runtime/main.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManagerChannelProvider.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Sources/GRPC/GRPCTLSConfiguration.swift
  Sources/GRPC/PlatformSupport.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Sources/GRPC/TLSConfiguration.swift
  Sources/GRPCConnectionBackoffInteropTest/main.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestClientConnection.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestServer.swift
  Sources/GRPCSampleData/bundle.p12
  Tests/GRPCTests/ALPNConfigurationTests.swift
  Tests/GRPCTests/BasicEchoTestCase.swift
  Tests/GRPCTests/ClientTLSFailureTests.swift
  Tests/GRPCTests/ClientTLSTests.swift
  Tests/GRPCTests/GRPCNetworkFrameworkTests.swift
  Tests/GRPCTests/GRPCServerPipelineConfiguratorTests.swift
  Tests/GRPCTests/PlatformSupportTests.swift
  Tests/GRPCTests/ServerTLSErrorTests.swift
  Tests/GRPCTests/ZeroLengthWriteTests.swift
  docs/apple-platforms.md
  docs/tls.md
Labels: semver-minor ↑

#1222 Bump version number to 1.3.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1223 Update Cocoapods for 1.3.0
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
  scripts/build_podspecs.py
Labels: semver-noop

#1225 Add connect which defaults port to 443 when using TLS
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
Labels: semver-minor ↑

#1226 Add setting for max number of concurrent streams for HTTP/2 connection
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Tests/GRPCTests/HTTP2MaxConcurrentStreamsTests.swift
Labels: semver-minor ↑

#1227 Avoid CoWs in grpc-web-to-http2
  Sources/GRPC/GRPCWebToHTTP2ServerCodec.swift
Labels: semver-patch •
