Repository grpc/grpc-swift, pull requests merged in 2021-09, with the labels that each got.

#1245 Add an internal pausable writer
  Sources/GRPC/AsyncAwaitSupport/AsyncWriter.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncWriterTests.swift
Labels: semver-patch •

#1249 [async-await] Base types for server implementation
  Sources/GRPC/AsyncAwaitSupport/CancellationError+GRPCStatusTransformable.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerCallContext.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Sources/GRPC/AsyncAwaitSupport/PassthroughMessageSource.swift
  Sources/GRPC/CallHandlers/BidirectionalStreamingServerHandler.swift
  Tests/GRPCTests/GRPCAsyncServerHandlerTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-minor ↑

#1253 New configuration parameter for HTTP2 maxFrameSize.
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
Labels: semver-minor ↑

#1255 Expose more http/2 configuration knobs
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManagerChannelProvider.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
  Tests/GRPCTests/ConfigurationTests.swift
Labels: semver-minor ↑

#1248 Raise the default HTTP/2 target window size
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/Server.swift
  Sources/GRPC/ServerBuilder.swift
Labels: semver-patch •

#1256 Bump version number to 1.4.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1257 Update CocoaPods for 1.4.0
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
Labels: semver-noop

#1259 Code generation for async-await
  Sources/protoc-gen-grpc-swift/Generator-Client+AsyncAwait.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Sources/protoc-gen-grpc-swift/Generator-Names.swift
  Sources/protoc-gen-grpc-swift/Generator-Server+AsyncAwait.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  Sources/protoc-gen-grpc-swift/Types.swift
  Sources/protoc-gen-grpc-swift/options.swift
Labels: semver-patch •

#1260 Generate async echo client and server, add async server implementation and basic tests
  Makefile
  Sources/Examples/Echo/Implementation/EchoAsyncProvider.swift
  Sources/Examples/Echo/Model/echo.grpc.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncIntegrationTests.swift
Labels: semver-patch •

#1263 Update swift-argument-parser version
  Package.swift
Labels: semver-minor ↑

#1262 [async-await] Support for sending response headers via context
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerCallContext.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncUnaryCall.swift
  Tests/GRPCTests/GRPCAsyncServerHandlerTests.swift
Labels: semver-minor ↑

#1266 Remove unused imports
  Sources/GRPC/GRPCChannel/GRPCChannel.swift
  Sources/GRPC/TLSVerificationHandler.swift
Labels: semver-patch •

#1264 Replace the placeholder client request and response mechanisms
  Sources/GRPC/AsyncAwaitSupport/AsyncWriter.swift
  Sources/GRPC/AsyncAwaitSupport/Call+AsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncIntegrationTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncWriterTests.swift
  Tests/GRPCTests/GRPCAsyncClientCallTests.swift
Labels: semver-minor ↑

#1265 Extend lifetime of client interceptor pipeline
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ClientCallTests.swift
  Tests/GRPCTests/ClientCancellingTests.swift
  Tests/GRPCTests/EchoHelpers/Interceptors/EchoInterceptorFactories.swift
  Tests/GRPCTests/InterceptedRPCCancellationTests.swift
Labels: semver-patch •

#1267 Bump version number to 1.4.1
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1268 Update pods for 1.4.1
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
Labels: semver-noop

#1261 [async-await] Code generation for "simple, but safe" wrapper client calls.
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCChannel+AsyncAwaitSupport.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCClient+AsyncAwaitSupport.swift
  Sources/protoc-gen-grpc-swift/Generator-Client+AsyncAwait.swift
  Sources/protoc-gen-grpc-swift/Generator-Client.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncIntegrationTests.swift
Labels: semver-minor ↑

#1269 Add note to README about async/await support.
  README.md
  docs/plugin.md
Labels: semver-noop

#1275 Log connectivity changes at debug level
  Sources/GRPC/ConnectivityState.swift
Labels: semver-patch •

#1277 Update compiler guards for concurrency
  Sources/Examples/Echo/Implementation/EchoAsyncProvider.swift
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncWriter.swift
  Sources/GRPC/AsyncAwaitSupport/Call+AsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/CancellationError+GRPCStatusTransformable.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerCallContext.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncUnaryCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCChannel+AsyncAwaitSupport.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCClient+AsyncAwaitSupport.swift
  Sources/GRPC/AsyncAwaitSupport/PassthroughMessageSequence.swift
  Sources/GRPC/AsyncAwaitSupport/PassthroughMessageSource.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
Labels: semver-patch •

#1272 [async-await] Added generation of interceptors
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator-Client+AsyncAwait.swift
  Tests/GRPCTests/AsyncAwaitSupport/InterceptorsAsyncTests.swift
  Tests/GRPCTests/Codegen/Normalization/normalization.grpc.swift
  Tests/GRPCTests/InterceptorsTests.swift
Labels: semver-patch •

#1279 Drop user context when closing client interceptor pipeline
  .github/workflows/ci.yaml
  Performance/allocations/tests/shared/Common.swift
  Performance/allocations/tests/test_unary_1k_ping_pong.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPCPerformanceTests/Benchmarks/MinimalEchoProvider.swift
Labels: semver-patch •

#1280 Bump version number to 1.4.2
  Sources/GRPC/Version.swift
  dev/version-bump.commit.template
Labels: semver-patch •

#1281 Update Cocoapods for 1.4.2
  CGRPCZlib.podspec
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
Labels: semver-noop
