Repository grpc/grpc-swift, pull requests merged in 2021-10, with the labels that each got.

#1278 Add Echo server and client example using async-await API
  Package.swift
  Sources/Examples/Echo/AsyncAwaitRuntime/ArgumentParser+AsyncAwait.swift
  Sources/Examples/Echo/AsyncAwaitRuntime/main.swift
  Sources/Examples/Echo/README.md
Labels: semver-noop

#1286 Update NIO dependencies in QPSBenchmark
  Performance/QPSBenchmark/Package.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncClient.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncPingPongRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncServer.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncUnaryRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/BenchmarkServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ClientInterface.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ClientUtilities.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/QPSWorker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/RequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/ServerInterface.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/WorkerServiceImpl.swift
Labels: semver-noop

#1289 Wire up connection backoff of channel pool
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/ConnectionPool/PooledChannel.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/ConnectionPool/PoolManagerStateMachineTests.swift
Labels: semver-patch •

#1276 Remove `_NIOConcurrency` import
  Package.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
Labels: semver-patch •

#1291 Bump version number to 1.4.1-async-await.2
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1290 Add a 'cause' to 'GRPCStatus'
  Sources/GRPC/GRPCStatus.swift
  Tests/GRPCTests/GRPCStatusTests.swift
Labels: semver-minor ↑

#1292 Provide more context to failing RPCs from the connection pool
  Sources/GRPC/ConnectionManager+Delegates.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectivityState.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/ConnectionPool/GRPCChannelPoolTests.swift
  Tests/GRPCTests/GRPCStatusTests.swift
Labels: semver-patch •
