Repository grpc/grpc-swift, pull requests merged in 2021-08, with the labels that each got.

#1232 Fix link for TLS docs in apple-platforms.md
  docs/apple-platforms.md
Labels: semver-noop

#1233 Fix watchOS availability guard for Network.framework TLS
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/GRPCTLSConfiguration.swift
  Sources/GRPC/ServerBuilder.swift
  Tests/GRPCTests/GRPCNetworkFrameworkTests.swift
  docs/tls.md
Labels: semver-patch •

#1238 Prepare CI for async/await.
  .github/workflows/ci.yaml
Labels: semver-noop

#1240 Update README badges
  README.md
Labels: semver-noop

#1244 Add explicit dependency on NIOTLS
  Package.swift
Labels: semver-patch •

#1243 Async-await: Base types for client implementation
  Package.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncUnaryCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCChannel+AsyncAwaitSupport.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCClient+AsyncAwaitSupport.swift
  Sources/GRPC/ClientCalls/ResponseContainers.swift
  Tests/GRPCTests/GRPCAsyncClientCallTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-minor ↑
