Repository grpc/grpc-swift, pull requests merged in 2021-11, with the labels that each got.

#1306 Add 'cause' to more transformed statuses
  Sources/GRPC/GRPCError.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
Labels: semver-patch •

#1308 Allow clients to shutdown gracefully
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/ConnectionPool/PooledChannel.swift
  Sources/GRPC/EventLoopFuture+RecoverFromUncleanShutdown.swift
  Sources/GRPC/GRPCChannel/GRPCChannel.swift
  Sources/GRPC/GRPCIdleHandlerStateMachine.swift
  Tests/GRPCTests/ClientQuiescingTests.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/EchoHelpers/EchoMessageHelpers.swift
  Tests/GRPCTests/GRPCIdleHandlerStateMachineTests.swift
Labels: semver-minor ↑

#1309 Use more accurate imports
  Package.swift
  Sources/Examples/Echo/Implementation/EchoProvider.swift
  Sources/Examples/Echo/Implementation/Interceptors.swift
  Sources/Examples/Echo/Runtime/main.swift
  Sources/Examples/HelloWorld/Client/main.swift
  Sources/Examples/HelloWorld/Server/GreeterProvider.swift
  Sources/Examples/HelloWorld/Server/main.swift
  Sources/Examples/PacketCapture/main.swift
  Sources/Examples/RouteGuide/Client/main.swift
  Sources/Examples/RouteGuide/Server/RouteGuideProvider.swift
  Sources/Examples/RouteGuide/Server/main.swift
  Sources/GRPC/ConnectionPool/PooledChannel.swift
  Sources/GRPCConnectionBackoffInteropTest/main.swift
  Sources/GRPCInteroperabilityTests/main.swift
  Sources/GRPCInteroperabilityTestsImplementation/Assertions.swift
  Sources/GRPCInteroperabilityTestsImplementation/GRPCTestingConvenienceMethods.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCase.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCases.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestClientConnection.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCredentials.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestServer.swift
  Sources/GRPCInteroperabilityTestsImplementation/ServerFeatures.swift
  Sources/GRPCInteroperabilityTestsImplementation/TestServiceProvider.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedClientThroughput.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedServer.swift
  Sources/GRPCPerformanceTests/Benchmarks/MinimalEchoProvider.swift
  Sources/GRPCPerformanceTests/Benchmarks/PercentEncoding.swift
  Sources/GRPCPerformanceTests/Benchmarks/ServerProvidingBenchmark.swift
  Sources/GRPCPerformanceTests/Benchmarks/UnaryThroughput.swift
  Sources/GRPCPerformanceTests/main.swift
  Sources/GRPCSampleData/GRPCSwiftCertificate.swift
  Tests/GRPCTests/ConnectionPool/GRPCChannelPoolTests.swift
Labels: semver-patch •

#1310 Remove client didSet state transition check
  Sources/GRPC/GRPCClientStateMachine.swift
Labels: semver-patch •

#1307 test: Add tests to verify mTLS behaviour
  Sources/GRPCSampleData/GRPCSwiftCertificate.swift
  Tests/GRPCTests/BasicEchoTestCase.swift
  Tests/GRPCTests/MutualTLSTests.swift
  scripts/makecert
Labels: semver-patch •

#1313 Update CI for 5.5
  .github/workflows/ci.yaml
Labels: semver-noop

#1312 Extend interoperability tests to use async provider
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/GRPCInteroperabilityTestModels/generate.sh
  Sources/GRPCInteroperabilityTestModels/unimplemented_call.patch
  Sources/GRPCInteroperabilityTestsImplementation/TestServiceAsyncProvider.swift
  Tests/GRPCTests/GRPCInteroperabilityTests.swift
Labels: semver-patch •

#1314 Bump version number to 1.6.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1317 Deflake zero length write tests
  Tests/GRPCTests/ZeroLengthWriteTests.swift
Labels: semver-noop

#1318 gPRC swift protobuf easy installation + easy file generataions
  README.md
Labels: semver-noop
