Repository grpc/grpc-swift, pull requests merged in 2021-01, with the labels that each got.

#1090 Avoid copying server interceptor context
  Sources/GRPC/Interceptor/MessageParts.swift
  Sources/GRPC/Interceptor/ServerInterceptorContext.swift
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ServerInterceptors.swift
Labels: semver-patch •

#1091 Server interceptors micro optimisation
  Sources/GRPC/Interceptor/ServerInterceptorPipeline.swift
Labels: semver-patch •

#1092 Avoid copying client interceptor contexts
  Sources/GRPC/ClientCalls/CallDetails.swift
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientInterceptors.swift
  Sources/GRPC/Interceptor/MessageParts.swift
  Sources/GRPC/TimeLimit.swift
Labels: semver-patch •

#1093 Scaffolding for better server codegen
  Sources/GRPC/CallHandlers/ServerHandlerProtocol.swift
  Sources/GRPC/CallHandlers/UnaryServerHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCStateMachine.swift
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/ServerErrorProcessor.swift
  Tests/GRPCTests/ClientTransportTests.swift
  Tests/GRPCTests/HTTP2ToRawGRPCStateMachineTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-minor ↑

#1095 Add a client streaming server handler
  Sources/GRPC/CallHandlers/ClientStreamingServerHandler.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-minor ↑

#1096 Add a handful more perf tests.
  Package.swift
  Sources/GRPCPerformanceTests/Benchmarks/EmbeddedServer.swift
  Sources/GRPCPerformanceTests/Benchmarks/MinimalEchoProvider.swift
  Sources/GRPCPerformanceTests/Benchmarks/UnaryThroughput.swift
  Sources/GRPCPerformanceTests/main.swift
Labels: semver-noop

#1097 Add a server streaming server handler.
  Sources/GRPC/CallHandlers/ServerStreamingServerHandler.swift
  Sources/GRPC/Compression/MessageEncoding.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-minor ↑

#1098 Add a bidirectional streaming server handler.
  Sources/GRPC/CallHandlers/BidirectionalStreamingServerHandler.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-minor ↑

#1100 Simplify some of the interaction between HTTP2 to GRPC state machine …
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCStateMachine.swift
  Tests/GRPCTests/HTTP2ToRawGRPCStateMachineTests.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-patch •

#1101 Support new handlers in the server codec + state machine
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCStateMachine.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-patch •

#1102 Fix some bugs with new handlers
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/BidirectionalStreamingServerHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingServerHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingServerHandler.swift
  Sources/GRPC/CallHandlers/UnaryServerHandler.swift
  Sources/GRPC/Compression/MessageEncoding.swift
  Sources/GRPC/GRPCError.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-patch •

#1106 Raise minimum Swift version to 5.2
  .swiftformat
  .travis.yml
  Examples/PCAPExample/Package.swift
  Package.swift
  Performance/QPSBenchmark/Package.swift
  README.md
Labels: semver-major ⚠️

#1110 Emit fewer flushes when handling RPCs on the server
  Sources/GRPC/CallHandlers/BidirectionalStreamingServerHandler.swift
  Sources/GRPC/CallHandlers/ClientStreamingServerHandler.swift
  Sources/GRPC/CallHandlers/ServerHandlerProtocol.swift
  Sources/GRPC/CallHandlers/ServerStreamingServerHandler.swift
  Sources/GRPC/CallHandlers/UnaryServerHandler.swift
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Tests/GRPCTests/HTTP2ToRawGRPCStateMachineTests.swift
  Tests/GRPCTests/UnaryServerHandlerTests.swift
Labels: semver-patch •

#1107 Added support for NIOSSLCustomVerificationCallback for client connection
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
  Sources/GRPC/TLSConfiguration.swift
  Tests/GRPCTests/ClientTLSFailureTests.swift
Labels: semver-minor ↑

#1111 Update Cocoapods
  CGRPCZlib.podspec
  README.md
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
  scripts/build_podspecs.py
Labels: semver-noop

#1113 Drop support for the old way of handling RPCs on the server
  Sources/GRPC/HTTP2ToRawGRPCServerCodec.swift
  Sources/GRPC/HTTP2ToRawGRPCStateMachine.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-patch •

#1115 Remove deprecated/dead code
  Sources/GRPC/CallHandlers/BidirectionalStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/CallHandlerFactory.swift
  Sources/GRPC/CallHandlers/ClientStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/ServerStreamingCallHandler.swift
  Sources/GRPC/CallHandlers/UnaryCallHandler.swift
  Sources/GRPC/CallHandlers/_BaseCallHandler.swift
  Sources/GRPC/GRPCServerRequestRoutingHandler.swift
  Sources/GRPC/ServerCallContexts/ServerCallContext.swift
  Sources/GRPC/ServerCallContexts/StreamingResponseCallContext.swift
  Sources/GRPC/ServerCallContexts/UnaryResponseCallContext.swift
  Sources/GRPC/Shims.swift
  Sources/GRPC/TimeLimit.swift
Labels: semver-major ⚠️

#1116 Add documentation about public API and compatability guarantees
  docs/api.md
Labels: semver-noop

#1118 Use swift-argument-parser for examples etc
  .travis-script.sh
  Package.swift
  Sources/Examples/Echo/README.md
  Sources/Examples/Echo/Runtime/main.swift
  Sources/Examples/HelloWorld/Client/main.swift
  Sources/Examples/HelloWorld/README.md
  Sources/Examples/HelloWorld/Server/main.swift
  Sources/Examples/RouteGuide/Client/main.swift
  Sources/Examples/RouteGuide/README.md
  Sources/Examples/RouteGuide/Server/main.swift
  Sources/GRPCConnectionBackoffInteropTest/main.swift
  Sources/GRPCInteroperabilityTests/main.swift
  Sources/GRPCPerformanceTests/main.swift
  docs/interceptors-tutorial.md
  docs/quick-start.md
Labels: semver-noop
