Repository grpc/grpc-swift, pull requests merged in 2022-06, with the labels that each got.

#1429 Make `Sendable` protocols `@preconcurrency`
  Sources/GRPC/AsyncAwaitSupport/GRPCSendable.swift
  Sources/GRPC/ClientErrorDelegate.swift
  Sources/GRPC/ConnectivityState.swift
  Sources/GRPC/GRPCChannel/GRPCChannel.swift
  Sources/GRPC/GRPCClient.swift
Labels: semver-minor ↑

#1430 Fix deprecation warnings
  Tests/GRPCTests/StreamResponseHandlerRetainCycleTests.swift
  Tests/GRPCTests/WithConnectedSocketTests.swift
Labels: semver-noop

#1432 Remove unused CI
  .github/workflows/ci.yaml
Labels: semver-noop

#1433 Update README
  README.md
Labels: semver-noop

#1434 Update generated code for interop tests
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
Labels: semver-patch •

#1437 Update version to 1.8.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1438 Add nightly 5.7 CI
  .github/workflows/ci.yaml
Labels: semver-noop

#1439 Remove Cocoapods script and references
  CGRPCZlib.podspec
  Examples/Google/SpeechToText/README.md
  README.md
  docs/plugin.md
  gRPC-Swift-Plugins.podspec
  gRPC-Swift.podspec
  scripts/build_podspecs.py
  scripts/bundle-plugins-for-release.sh
Labels: semver-noop

#1441 Build release plugins as universal binaries
  scripts/bundle-plugins-for-release.sh
Labels: semver-noop

#1444 Raise minimum NIO version to 2.36.0
  Package.swift
Labels: semver-patch •

#1442 Update p12 bundle for tests
  Sources/GRPCSampleData/bundle.p12
Labels: semver-noop
