Repository grpc/grpc-swift, pull requests merged in 2022-02, with the labels that each got.

#1355 Remove perf tests for 5.2
  .github/workflows/ci.yaml
Labels: semver-noop

#1354 Add more flexibility to perf tests
  Package.swift
  Sources/GRPCPerformanceTests/Benchmarks/ServerProvidingBenchmark.swift
  Sources/GRPCPerformanceTests/Benchmarks/UnaryThroughput.swift
  Sources/GRPCPerformanceTests/main.swift
Labels: semver-noop

#1356 Add cause to GRPCStatus.processingError for uncaught errors
  Sources/GRPC/GRPCStatus.swift
  Sources/GRPC/ServerErrorProcessor.swift
Labels: semver-minor ↑

#1357 Add cause to GRPCStatus.descrpition if it is non-nil
  Sources/GRPC/GRPCStatus.swift
  Tests/GRPCTests/GRPCStatusTests.swift
Labels: semver-patch •

#1358 Bump version number to 1.7.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1359 Update minimum HTTP/2 version
  Package.swift
Labels: semver-patch •

#1360 Bump version number to 1.7.1
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1361 protoc-gen-grpc-swift: FileHandle for stdin, stdout
  Sources/protoc-gen-grpc-swift/io.swift
  Sources/protoc-gen-grpc-swift/main.swift
Labels: semver-patch •

#1363 Release stream callback, once the stream has finished
  Sources/GRPC/ClientCalls/ResponseContainers.swift
  Tests/GRPCTests/FakeChannelTests.swift
  Tests/GRPCTests/StreamResponseHandlerRetainCycleTests.swift
Labels: semver-patch •

#1348 Update allocation counter limits
  .github/workflows/ci.yaml
Labels: semver-noop

#1364 Lower availability/compiler guards
  Sources/Examples/Echo/AsyncAwaitRuntime/ArgumentParser+AsyncAwait.swift
  Sources/Examples/Echo/AsyncAwaitRuntime/main.swift
  Sources/Examples/Echo/Implementation/EchoAsyncProvider.swift
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/RouteGuide/Client/main.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/Examples/RouteGuide/Server/RouteGuideProvider.swift
  Sources/Examples/RouteGuide/Server/main.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncWriter.swift
  Sources/GRPC/AsyncAwaitSupport/Call+AsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/CancellationError+GRPCStatusTransformable.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerCallContext.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncUnaryCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCChannel+AsyncAwaitSupport.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCClient+AsyncAwaitSupport.swift
  Sources/GRPC/AsyncAwaitSupport/PassthroughMessageSequence.swift
  Sources/GRPC/AsyncAwaitSupport/PassthroughMessageSource.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/GRPCInteroperabilityTestsImplementation/TestServiceAsyncProvider.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
Labels: semver-patch •

#1365 Use correct naming for making async calls
  Sources/protoc-gen-grpc-swift/Generator-Client+AsyncAwait.swift
  Sources/protoc-gen-grpc-swift/Generator-Names.swift
Labels: semver-patch •
