Repository grpc/grpc-swift, pull requests merged in 2022-05, with the labels that each got.

#1394 Server handler interceptor state machine
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/ServerInterceptorStateMachine+Actions.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/ServerInterceptorStateMachine+Finished.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/ServerInterceptorStateMachine+Intercepting.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/ServerInterceptorStateMachine.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/StreamState.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/ServerInterceptorStateMachineStreamStateTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncServerHandler/ServerInterceptorStateMachine/ServerInterceptorStateMachineTests.swift
Labels: semver-patch •

#1397 Raise minimum supported Swift version to 5.4
  .github/workflows/ci.yaml
  FuzzTesting/Package.swift
  Package.swift
  Performance/QPSBenchmark/Package.swift
  README.md
  Tests/LinuxMain.swift
  scripts/build_podspecs.py
Labels: semver-minor ↑

#1399 Make all tests discoverable on Linux
  Tests/GRPCTests/FunctionalTests.swift
  Tests/GRPCTests/GRPCInteroperabilityTests.swift
  Tests/GRPCTests/ServerThrowingTests.swift
Labels: semver-noop

#1402 Migrate speech to text example app to swift package manager & fix compile errors
  Examples/Google/SpeechToText/Makefile
  Examples/Google/SpeechToText/Podfile
  Examples/Google/SpeechToText/Podfile.lock
  Examples/Google/SpeechToText/README.md
  Examples/Google/SpeechToText/Sources/SpeechService.swift
  Examples/Google/SpeechToText/SpeechToText-gRPC-iOS.xcodeproj/project.pbxproj
  Examples/Google/SpeechToText/SpeechToText-gRPC-iOS.xcodeproj/xcshareddata/xcschemes/SpeechToText-gRPC-iOS.xcscheme
  Examples/Google/SpeechToText/SpeechToText-gRPC-iOS.xcworkspace/contents.xcworkspacedata
  Examples/Google/SpeechToText/SpeechToText-gRPC-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: semver-noop

#1415 Don't fail on cancellation
  Sources/GRPC/ClientCalls/Call.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Tests/GRPCTests/ClientCallTests.swift
Labels: semver-patch •
