Repository grpc/grpc-swift, pull requests merged in 2022-10, with the labels that each got.

#1496 Remove invalid command line args from the example
  docs/basic-tutorial.md
Labels: semver-noop

#1499 Allow to write a sequence of requests/responses
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStreamWriter.swift
  Tests/GRPCTests/GRPCAsyncClientCallTests.swift
  Tests/GRPCTests/GRPCAsyncServerHandlerTests.swift
Labels: semver-minor ↑

#1505 Fix HelloWorld Samples
  Sources/Examples/HelloWorld/Client/helloworldclient.swift
  Sources/Examples/HelloWorld/Server/HelloWorldServer.swift
Labels: semver-noop

#1506 Revert "Fix HelloWorld Samples (#1505)"
  Sources/Examples/HelloWorld/Client/main.swift
  Sources/Examples/HelloWorld/Server/main.swift
Labels: semver-noop

#1504 Allow to `finish()` GRPCAsyncRequestStreamWriter sync, non-throwing
  Sources/Examples/RouteGuide/Client/RouteGuideClient.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCClient+AsyncAwaitSupport.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncClientTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncIntegrationTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/InterceptorsAsyncTests.swift
  Tests/GRPCTests/GRPCAsyncClientCallTests.swift
Labels: semver-minor ↑

#1509 Log TLS version
  Package.swift
  Package@swift-5.5.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
  Sources/GRPC/TLSVersion.swift
Labels: semver-patch •

#1512 Fix HelloWorld examples
  Sources/Examples/HelloWorld/Client/HelloWorldClient.swift
  Sources/Examples/HelloWorld/Server/HelloWorldServer.swift
Labels: semver-noop

#1513 Fix sendable warnings
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionPool/GRPCChannelPool.swift
  Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift
Labels: semver-patch •

#1516 Bump version number to 1.12.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1515 Add a connection pool delegate
  Sources/GRPC/ConnectionManager+Delegates.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectionPool/ConnectionManagerID.swift
  Sources/GRPC/ConnectionPool/ConnectionPool+PerConnectionState.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectionPool/GRPCChannelPool.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/ConnectionPool/PooledChannel.swift
  Sources/GRPC/GRPCIdleHandler.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolDelegates.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/ConnectionPool/GRPCChannelPoolTests.swift
  Tests/GRPCTests/ConnectionPool/PoolManagerStateMachineTests.swift
Labels: semver-minor ↑
