Repository grpc/grpc-swift, pull requests merged in 2022-07, with the labels that each got.

#1453 Use swift-atomics
  Performance/QPSBenchmark/Package.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncClient.swift
  Tests/GRPCTests/StreamResponseHandlerRetainCycleTests.swift
Labels: semver-noop

#1456 Provide an error when cancelling async writer
  Sources/GRPC/AsyncAwaitSupport/AsyncWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncClientTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncWriterTests.swift
Labels: semver-patch •

#1462 Make path available in async calls
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncUnaryCall.swift
Labels: semver-minor ↑
