Repository grpc/grpc-swift, pull requests merged in 2022-08, with the labels that each got.

#1465 Bump version number to 1.9.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1469 Remove warnings from Package.swift
  Package.swift
  Package@swift-5.4.swift
  Package@swift-5.5.swift
Labels: semver-patch •

#1470 Add async version of QPS Benchmark Service
  Performance/QPSBenchmark/Package.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.grpc.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.grpc.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncBenchmarkServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/AsyncServer.swift
Labels: semver-noop

#1471 Add async implementation of QPSBenchmark
  Performance/QPSBenchmark/Package.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncClientProtocol.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncPingPongRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncQPSClientImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncQPSServerImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncServerProtocol.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncUnaryRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Async/AsyncWorkerServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOBenchmarkServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOClientProtocol.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOPingPongRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOQPSClientImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOQPSServerImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIORequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOServerProtocol.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOUnaryRequestMaker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/NIO/NIOWorkerServiceImpl.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/QPSWorker.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/Stats.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Runtime/main.swift
Labels: semver-noop

#1474 Add SPM plugin for GRPC code generation
  Package.swift
  Plugins/GRPCSwiftPlugin/plugin.swift
  Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md
Labels: semver-minor ↑

#1475 Add GRPC and protobuf SPM plugins to QPSBenchmark
  Performance/QPSBenchmark/Makefile
  Performance/QPSBenchmark/Package.swift
  Performance/QPSBenchmark/README.md
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.grpc.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/benchmark_service.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/control.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/control.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/core_stats.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/messages.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/payloads.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/stats.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/stats.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.grpc.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.pb.swift
  Performance/QPSBenchmark/Sources/QPSBenchmark/Model/worker_service.proto
  Performance/QPSBenchmark/Sources/QPSBenchmark/grpc-swift-config.json
  Performance/QPSBenchmark/Sources/QPSBenchmark/swift-protobuf-config.json
Labels: semver-noop
