Repository grpc/grpc-swift, pull requests merged in 2022-09, with the labels that each got.

#1476 Log when receiving GOAWAY frames
  Sources/GRPC/GRPCIdleHandler.swift
  Sources/GRPC/Logger.swift
Labels: semver-patch •

#1480 Fix preconcurrency warnings
  Package.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerCallContext.swift
  Sources/GRPC/CallOptions.swift
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/ConnectionKeepalive.swift
  Sources/GRPC/ConnectionPool/GRPCChannelPool.swift
  Sources/GRPC/PlatformSupport.swift
  Sources/GRPC/TimeLimit.swift
Labels: semver-noop

#1481 Bump version number to 1.10.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1488 Clarify relative paths for SPM plugin docs
  Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md
Labels: semver-noop

#1483 Raise minimum Swift version to 5.5
  .github/workflows/ci.yaml
  FuzzTesting/Package.swift
  Package@swift-5.4.swift
  README.md
  Sources/GRPC/Docs.docc/index.md
Labels: semver-minor ↑

#1485 Expose public creation methods for `GRPCAsyncRequestStream` and `GRPCAsyncResponseStreamWriter`
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStreamWriter.swift
  Sources/GRPC/Interceptor/ClientTransportFactory.swift
  Tests/GRPCTests/AsyncAwaitSupport/GRPCAsyncRequestStreamTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/GRPCAsyncResponseStreamWriterTests.swift
Labels: semver-minor ↑

#1482 Use forward looking SwiftProtobuf API
  Package.swift
  Package@swift-5.5.swift
  Sources/protoc-gen-grpc-swift/StreamingType.swift
  Sources/protoc-gen-grpc-swift/main.swift
Labels: semver-patch •

#1490 Update swift-nio version, allocation test max values and alloc-limits.sh
  .github/workflows/ci.yaml
  Package.swift
  Package@swift-5.5.swift
  Performance/allocations/tests/test_bidi_1k_rpcs.swift
  Sources/GRPC/AsyncAwaitSupport/PassthroughMessageSource.swift
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/ConnectivityState.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncWriterTests.swift
  Tests/GRPCTests/CapturingLogHandler.swift
  Tests/GRPCTests/ClientQuiescingTests.swift
  Tests/GRPCTests/ConnectionPool/GRPCChannelPoolTests.swift
  Tests/GRPCTests/ConnectionPool/PoolManagerStateMachineTests.swift
  Tests/GRPCTests/ErrorRecordingDelegate.swift
  Tests/GRPCTests/StreamResponseHandlerRetainCycleTests.swift
  scripts/alloc-limits.sh
Labels: semver-noop

#1492 Use a C executable for fuzz testing
  FuzzTesting/Package.swift
  FuzzTesting/Sources/ServerFuzzer/src/serverfuzzer.c
  FuzzTesting/Sources/ServerFuzzerLib/ServerFuzzer.swift
Labels: semver-noop

#1493 Adopt NIOAsyncWriter
  Sources/GRPC/AsyncAwaitSupport/AsyncWriter.swift
  Sources/GRPC/AsyncAwaitSupport/Call+AsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncRequestStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStream.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStreamWriter.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncWriterSinkDelegate.swift
  Sources/GRPC/AsyncAwaitSupport/NIOAsyncWrappers.swift
  Sources/GRPC/ServerErrorProcessor.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncWriterTests.swift
  Tests/GRPCTests/GRPCAsyncServerHandlerTests.swift
Labels: semver-patch •

#1495 Bump version number to 1.11.0
  Sources/GRPC/Version.swift
Labels: semver-patch •
