Repository grpc/grpc-swift, pull requests merged in 2023-07, with the labels that each got.

#1621 Add support for `XcodeProjectPlugin`
  Plugins/GRPCSwiftPlugin/plugin.swift
  Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md
Labels: semver-minor ↑

#1627 Update expired test certs
  Sources/GRPCSampleData/GRPCSwiftCertificate.swift
  Sources/GRPCSampleData/bundle.p12
Labels: semver-noop

#1626 Only schedule a close if the ping was actually sent
  Sources/GRPC/GRPCIdleHandler.swift
Labels: semver-patch •

#1629 Add note about SPM plugin known issues, provide better errors
  Plugins/GRPCSwiftPlugin/plugin.swift
  Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md
Labels: semver-patch •
