Repository grpc/grpc-swift, pull requests merged in 2023-12, with the labels that each got.

#1732 Make the reflection service a product
  Package.swift
Labels: semver-minor ↑

#1734 Make the retry throttle optional
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessServerTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
Labels: v2

#1737 Add public API to create connection IDs
  Sources/GRPC/ConnectionPool/GRPCChannelPool.swift
Labels: semver-minor ↑

#1741 Bump version number to 1.21.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1746 Update available to fix build for non-macOS Apple platforms
  Sources/Examples/PacketCapture/PacketCapture.swift
  Tests/GRPCCodeGenTests/Internal/Translator/SnippetBasedTranslatorTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TestFunctions.swift
  Tests/GRPCCoreTests/Call/Client/ClientResponseTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerRequestTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerResponseTests.swift
  Tests/GRPCCoreTests/ServerErrorTests.swift
  Tests/GRPCCoreTests/Streaming/Internal/AsyncSequenceOfOne.swift
  Tests/GRPCCoreTests/Streaming/Internal/BufferedStreamTests.swift
  Tests/GRPCCoreTests/Test Utilities/AsyncSequence+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Client/ClientInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Server/ServerInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/RPCAsyncSequence+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/RPCWriter+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/Services/BinaryEcho.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
  Tests/GRPCCoreTests/TimeoutTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
  Tests/GRPCInProcessTransportTests/Test Utilities/XCTest+Utilities.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachineTests.swift
  Tests/GRPCTests/EchoMetadataTests.swift
  Tests/GRPCTests/GRPCAsyncClientCallTests.swift
  Tests/GRPCTests/GRPCAsyncServerHandlerTests.swift
  Tests/GRPCTests/GRPCNetworkFrameworkTests.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceIntegrationTests.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceUnitTests.swift
  Tests/GRPCTests/ServerTLSErrorTests.swift
Labels: semver-noop
