Repository grpc/grpc-swift, pull requests merged in 2023-06, with the labels that each got.

#1608 Increase cancellation support for async calls
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncBidirectionalStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncClientStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerStreamingCall.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncUnaryCall.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncClientTests.swift
  Tests/GRPCTests/AsyncAwaitSupport/XCTest+AsyncAwait.swift
  Tests/GRPCTests/InterceptedRPCCancellationTests.swift
Labels: semver-patch •

#1613 Handle non-200 status codes more gracefully
  Sources/GRPC/GRPCClientChannelHandler.swift
  Sources/GRPC/GRPCClientStateMachine.swift
  Sources/GRPC/GRPCError.swift
  Tests/GRPCTests/GRPCClientStateMachineTests.swift
  Tests/GRPCTests/GRPCStatusCodeTests.swift
Labels: semver-patch •

#1614 Bump version number to 1.17.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1612 Remove the gRPC Authors copyright header from generated swift files
  Examples/Google/NaturalLanguage/Sources/language_service.grpc.swift
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  Tests/GRPCTests/Codegen/Normalization/normalization.grpc.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
  dev/codegen-tests/06-test-client-only/golden/test.grpc.swift
  scripts/license-check.sh
Labels: semver-patch •

#1616 Relax AsyncSequence.collect availability check
  Tests/GRPCTests/AsyncAwaitSupport/AsyncSequence+Helpers.swift
Labels: semver-noop

#1623 Make Server Sendable
  Sources/GRPC/Server.swift
Labels: semver-minor ↑

#1624 Fix comment formatting issue
  Sources/GRPC/Server.swift
Labels: semver-patch •
