Repository grpc/grpc-swift, pull requests merged in 2023-05, with the labels that each got.

#1595 Allow custom verification callback to be configured for servers
  Sources/GRPC/GRPCTLSConfiguration.swift
  Sources/GRPC/Server.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncClientTests.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/ServerTLSErrorTests.swift
Labels: semver-minor ↑

#1594 Allow for more CORS configuration
  Sources/GRPC/Server.swift
  Sources/GRPC/WebCORSHandler.swift
  Tests/GRPCTests/WebCORSHandlerTests.swift
Labels: semver-minor ↑

#1596 Bump version number to 1.16.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1600 Fix warnings from nightly Swift builds
  Sources/GRPC/ClientConnection.swift
  Sources/GRPC/Interceptor/ClientTransportFactory.swift
  Sources/GRPCInteroperabilityTestsImplementation/GRPCTestingConvenienceMethods.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCases.swift
  Tests/GRPCTests/XCTestHelpers.swift
Labels: semver-patch •

#1602 Allow network framework tests to be skipped when no user interaction
  Tests/GRPCTests/AsyncAwaitSupport/AsyncClientTests.swift
  Tests/GRPCTests/GRPCNetworkFrameworkTests.swift
Labels: semver-noop

#1603 Fix stream accounting bug when stream close leads to connection close
  Sources/GRPC/ConnectionPool/ConnectionPool+PerConnectionState.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
Labels: semver-patch •

#1605 Improve Sendable checking for server code
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPC/Interceptor/ServerInterceptors.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/GRPCInteroperabilityTestsImplementation/TestServiceAsyncProvider.swift
  Sources/protoc-gen-grpc-swift/Generator-Server+AsyncAwait.swift
  Sources/protoc-gen-grpc-swift/Generator-Server.swift
  Tests/GRPCTests/Codegen/Normalization/normalization.grpc.swift
  Tests/GRPCTests/EchoHelpers/Interceptors/EchoInterceptorFactories.swift
  Tests/GRPCTests/InterceptorsTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
Labels: semver-minor ↑

#1599 Allow server handlers to send response headers directly
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachine+Actions.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachine+Draining.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachine+Finished.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachine+Handling.swift
  Sources/GRPC/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachine.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerCallContext.swift
  Sources/GRPC/AsyncAwaitSupport/GRPCAsyncServerHandler.swift
  Tests/GRPCTests/AsyncAwaitSupport/AsyncServerHandler/ServerHandlerStateMachine/ServerHandlerStateMachineTests.swift
  Tests/GRPCTests/GRPCAsyncClientCallTests.swift
Labels: semver-minor ↑

#1606 Emit 'swift-format-ignore-file' in generated files to avoid having them reformatted by swift-format
  Examples/Google/NaturalLanguage/Sources/language_service.grpc.swift
  Sources/Examples/Echo/Model/echo.grpc.swift
  Sources/Examples/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/RouteGuide/Model/route_guide.grpc.swift
  Sources/GRPCInteroperabilityTestModels/Generated/test.grpc.swift
  Sources/protoc-gen-grpc-swift/Generator.swift
  Tests/GRPCTests/Codegen/Normalization/normalization.grpc.swift
  dev/codegen-tests/01-echo/golden/echo.grpc.swift
  dev/codegen-tests/02-multifile/golden/a.grpc.swift
  dev/codegen-tests/02-multifile/golden/b.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/a.grpc.swift
  dev/codegen-tests/03-multifile-with-module-map/golden/b.grpc.swift
  dev/codegen-tests/04-service-with-message-import/golden/service.grpc.swift
  dev/codegen-tests/05-service-only/golden/test.grpc.swift
  dev/codegen-tests/06-test-client-only/golden/test.grpc.swift
  scripts/license-check.sh
Labels: semver-patch •
