Repository grpc/grpc-swift, pull requests merged in 2023-10, with the labels that each got.

#1652 Add proposal for v2 stub design
  Sources/GRPC/Docs.docc/Proposals/0001-stub-api.md
Labels: semver-noop

#1657 Drop Swift 5.6
  .github/workflows/ci.yaml
  Package.swift
  Performance/QPSBenchmark/Package.swift
  README.md
  Sources/GRPC/Docs.docc/index.md
  Sources/GRPC/PlatformSupport.swift
  Sources/GRPC/Server.swift
Labels: semver-minor ↑

#1656 Add RPCError and Status
  Package.swift
  Sources/GRPCCore/Metadata.swift
  Sources/GRPCCore/RPCError.swift
  Sources/GRPCCore/Status.swift
  Tests/GRPCCoreTests/RPCErrorTests.swift
  Tests/GRPCCoreTests/StatusTests.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
Labels: semver-noop

#1659 Generated reflection service code
  Makefile
  Package.swift
  Sources/GRPCReflectionService/Model/reflection.grpc.swift
  Sources/GRPCReflectionService/Model/reflection.pb.swift
  Sources/GRPCReflectionService/Model/reflection.proto
  Sources/GRPCReflectionService/Server/ReflectionProvider.swift
Labels: semver-patch •

#1660 Add transport protocols and surrounding types
  Sources/GRPCCore/Call/ClientRPCExecutionConfiguration.swift
  Sources/GRPCCore/MethodDescriptor.swift
  Sources/GRPCCore/Stream/RPCAsyncSequence.swift
  Sources/GRPCCore/Stream/RPCWriter.swift
  Sources/GRPCCore/Stream/RPCWriterProtocol.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/RPCParts.swift
  Sources/GRPCCore/Transport/RPCStream.swift
  Sources/GRPCCore/Transport/ServerTransport.swift
  Tests/GRPCCoreTests/Call/ClientRPCExecutionConfigurationTests.swift
  Tests/GRPCCoreTests/MethodDescriptorTests.swift
  Tests/GRPCCoreTests/RPCPartsTests.swift
Labels: semver-noop

#1666 Add missing availability guards
  Sources/GRPCCore/Stream/RPCWriter.swift
  Sources/GRPCCore/Stream/RPCWriterProtocol.swift
Labels: semver-noop

#1665 Add client request and response objects
  Sources/GRPCCore/Call/ClientRequest.swift
  Sources/GRPCCore/Call/ClientResponse.swift
  Sources/GRPCCore/Stream/AsyncSequenceOfOne.swift
  Tests/GRPCCoreTests/Call/ClientRequestTests.swift
  Tests/GRPCCoreTests/Call/ClientResponseTests.swift
  Tests/GRPCCoreTests/Stream/AsyncSequenceOfOne.swift
  Tests/GRPCCoreTests/Test Utilities/AsyncSequence+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/RPCAsyncSequence+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/RPCWriter+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
Labels: semver-noop

#1667 Add server request and response objects
  Sources/GRPCCore/Call/ServerRequest.swift
  Sources/GRPCCore/Call/ServerResponse.swift
  Tests/GRPCCoreTests/Call/ServerRequestTests.swift
  Tests/GRPCCoreTests/Call/ServerResponseTests.swift
Labels: semver-noop

#1664 Message encoder/decoder
  Sources/GRPCCore/Coding/Coding.swift
  Tests/GRPCCoreTests/Coding/CodingTests.swift
  Tests/GRPCCoreTests/Test Utilities/Coding+JSON.swift
Labels: semver-noop

#1670 Add missing deque import
  Package.swift
Labels: semver-patch •

#1671 add concurrency avail guard to AsyncSequenceOfOne
  Sources/GRPCCore/Stream/AsyncSequenceOfOne.swift
Labels: semver-noop

#1672 ClientRPCExecutionConfigurationTests only available on macOS 13...
  Tests/GRPCCoreTests/Call/Client/ClientRPCExecutionConfigurationTests.swift
Labels: semver-noop

#1674 Add `package` visibility modifier
  Plugins/GRPCSwiftPlugin/plugin.swift
  Sources/protoc-gen-grpc-swift/options.swift
  docs/plugin.md
Labels: semver-patch •

#1676 Fix soundness script
  Tests/GRPCTests/InterceptedRPCCancellationTests.swift
  scripts/sanity.sh
Labels: semver-noop

#1678 Add support for ordo-one/package-benchmark
  .github/workflows/ci.yaml
  .gitignore
  Performance/Benchmarks/Benchmarks/GRPCSwiftBenchmark/Benchmarks.swift
  Performance/Benchmarks/Package.swift
  README.md
Labels: semver-noop

#1677 Implemented file-containing-extension request for Reflection Service
  Sources/GRPCReflectionService/Server/ReflectionService.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceIntegrationTests.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceUnitTests.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Utils.swift
Labels: semver-patch •

#1681 Vendor in NIOs lock
  NOTICES.txt
  Sources/GRPCCore/Internal/Concurrency Primities/Lock.swift
Labels: semver-noop

#1686 Allow binding to a socket address via server builder
  Sources/GRPC/ServerBuilder.swift
Labels: semver-minor ↑

#1687 Add backpressure aware async sequence
  NOTICES.txt
  Package.swift
  Sources/GRPCCore/Streaming/Internal/BufferedStream.swift
  Tests/GRPCCoreTests/Streaming/Internal/BufferedStreamTests.swift
  Tests/GRPCCoreTests/Test Utilities/AsyncSequence+Utilities.swift
Labels: semver-noop

#1685 Make the connection pool error public
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/GRPCStatusTests.swift
Labels: semver-minor ↑

#1688 Add helpers to convert between Status.Code and RPCError.Code
  Sources/GRPCCore/RPCError.swift
  Sources/GRPCCore/Status.swift
  Tests/GRPCCoreTests/RPCErrorTests.swift
  Tests/GRPCCoreTests/StatusTests.swift
Labels: semver-noop

#1684 Add a broadcast async sequence
  Package.swift
  Sources/GRPCCore/Call/Client/ClientResponse.swift
  Sources/GRPCCore/Streaming/Internal/AsyncSequenceOfOne.swift
  Sources/GRPCCore/Streaming/Internal/BroadcastAsyncSequence.swift
  Sources/GRPCCore/Streaming/RPCAsyncSequence.swift
  Sources/GRPCCore/Streaming/RPCWriter.swift
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Tests/GRPCCoreTests/Call/Client/ClientResponseTests.swift
  Tests/GRPCCoreTests/Streaming/Internal/AsyncSequenceOfOne.swift
  Tests/GRPCCoreTests/Streaming/Internal/BroadcastAsyncSequenceTests.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
Labels: semver-noop

#1689 Add a retry throttle
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/RetryThrottle.swift
  Tests/GRPCCoreTests/Transport/RetryThrottleTests.swift
Labels: semver-noop

#1683 Add Metadata collection
  NOTICES.txt
  Sources/GRPCCore/Internal/Base64.swift
  Sources/GRPCCore/Internal/Concurrency Primitives/Lock.swift
  Sources/GRPCCore/Internal/String+Extensions.swift
  Sources/GRPCCore/Metadata.swift
  Tests/GRPCCoreTests/MetadataTests.swift
  Tests/GRPCTests/GRPCTestCase.swift
Labels: semver-noop

#1696 Add missing availability annotations
  Sources/GRPCCore/Internal/Result+Catching.swift
  Tests/GRPCCoreTests/Internal/Result+CatchingTests.swift
Labels: semver-noop
