Repository grpc/grpc-swift, pull requests merged in 2023-11, with the labels that each got.

#1698 guard testPreviousRPCAttemptsValidValues
  Tests/GRPCCoreTests/Internal/Metadata+GRPCTests.swift
Labels: semver-noop

#1697 Convenience method to jitter keepalive interval
  Sources/GRPC/ConnectionKeepalive.swift
  Tests/GRPCTests/ConnectionManagerTests.swift
Labels: semver-minor ↑

#1700 Fix last peer initiated stream ID when quiescing
  Sources/GRPC/GRPCIdleHandlerStateMachine.swift
  Tests/GRPCTests/GRPCIdleHandlerStateMachineTests.swift
Labels: semver-patch •

#1701 Bump version number to 1.20.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1702 Add some missing Sendable annotations
  Sources/GRPC/ConnectionPool/ConnectionPool+Waiter.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/GRPCServerPipelineConfigurator.swift
Labels: semver-patch •

#1704 Add in-process server transport
  Sources/GRPCCore/Streaming/RPCWriter+Closable.swift
  Sources/GRPCCore/Transport/InProcessServerTransport.swift
  Tests/GRPCCoreTests/Transport/InProcessServerTransportTest.swift
Labels: v2

#1706 propagate availability guards
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+Transport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHasness+ServerBehavior.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
Labels: v2

#1709 Added availability check for OS version in unit tests for temporary directory path
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceUnitTests.swift
Labels: semver-noop

#1708 Add support for retries
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/RetryDelaySequence.swift
  Sources/GRPCCore/Streaming/Internal/BroadcastAsyncSequence+RPCWriter.swift
  Sources/GRPCCore/Streaming/Internal/BroadcastAsyncSequence.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Retries.swift
  Tests/GRPCCoreTests/Call/Client/RetryDelaySequenceTests.swift
Labels: v2

#1703 Adding support for v1alpha reflection
  Makefile
  Package.swift
  Sources/GRPCReflectionService/Server/ReflectionService.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1Alpha.swift
  Sources/GRPCReflectionService/v1/reflection-v1.grpc.swift
  Sources/GRPCReflectionService/v1/reflection-v1.pb.swift
  Sources/GRPCReflectionService/v1/reflection-v1.proto
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.grpc.swift
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.pb.swift
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.proto
  Tests/GRPCTests/GRPCReflectionServiceTests/Generated/v1/reflection-v1.grpc.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Generated/v1/reflection-v1.pb.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Generated/v1Alpha/reflection-v1alpha.grpc.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Generated/v1Alpha/reflection-v1alpha.pb.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceIntegrationTests.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Utils.swift
Labels: semver-patch •

#1694 Created README for the Reflection Service
  Makefile
  Package.swift
  Sources/Examples/ReflectionService/Generated/echo.grpc.reflection.txt
  Sources/Examples/ReflectionService/Generated/helloworld.grpc.reflection.txt
  Sources/Examples/ReflectionService/GreeterProvider.swift
  Sources/Examples/ReflectionService/ReflectionServer.swift
  Sources/GRPCReflectionService/Documentation.docc/ReflectionServiceTutorial.md
  Sources/GRPCReflectionService/Server/ReflectionService.swift
Labels: semver-patch •

#1713 Add in-process client transport
  Sources/GRPCCore/Call/Client/ClientRPCExecutionConfigurationCollection.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Streaming/RPCAsyncSequence.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/InProcessClientTransport.swift
  Sources/GRPCCore/Transport/InProcessServerTransport.swift
  Tests/GRPCCoreTests/Call/Client/ClientRPCExecutionConfigurationCollectionTests.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+Transport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCCoreTests/Transport/InProcessClientTransportTests.swift
  Tests/GRPCCoreTests/Transport/InProcessServerTransportTests.swift
Labels: v2

#1715 Add the server RPC executor.
  Package.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Internal/Metadata+GRPC.swift
  Sources/GRPCCore/Status.swift
  Sources/GRPCCore/Streaming/Internal/AsyncIteratorSequence.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+MessageToRPCResponsePart.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Server/ServerInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1714 Add support for hedging
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Internal/Task+SleepBackport.swift
  Sources/GRPCCore/Internal/TaskGroup+CancellableTask.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Hedging.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1717 Add the router and service protocol
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Call/Server/RegistrableRPCService.swift
  Tests/GRPCCoreTests/Call/Server/RPCRouterTests.swift
Labels: v2

#1720 Add missing available annotations to test code
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+Transport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Hedging.swift
  Tests/GRPCCoreTests/Transport/InProcessClientTransportTests.swift
Labels: v2

#1719 Fix Task sleep backport
  Sources/GRPCCore/Internal/Task+SleepBackport.swift
Labels: v2

#1716 Created the CodeGenerationRequest
  Package.swift
  Sources/GRPCCodeGen/CodeGenerationRequest.swift
Labels: v2

#1722 Bring over structured Swift syntax from OpenAPI
  NOTICES.txt
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
Labels: v2

#1723 Add SourceFile type for CodeGenLib
  Sources/GRPCCodeGen/SourceFile.swift
Labels: v2

#1724 Rename server
  Sources/GRPCCore/GRPCServer.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
Labels: v2

#1726 Added TypeName and TypeUsage from OpenAPI Generator.
  NOTICES.txt
  Sources/GRPCCodeGen/Internal/TypeName.swift
  Sources/GRPCCodeGen/Internal/TypeUsage.swift
Labels: v2

#1728 Brought CodeRenderer from OpenAPI Generator.
  NOTICES.txt
  Package.swift
  Sources/GRPCCodeGen/Internal/Renderer/RendererProtocol.swift
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCodeGen/Internal/TypeName.swift
  Tests/GRPCCodeGenTests/Internal/Renderer/TextBasedRendererTests.swift
Labels: v2
