Repository grpc/grpc-swift, pull requests merged in 2024-07, with the labels that each got.

#1956 Add integ test for SwiftPM plugin
  .github/workflows/ci.yaml
  scripts/run-plugin-tests.sh
Labels: semver-noop

#1955 Swift 6-ify the package manifest
  .github/workflows/ci.yaml
  Package.swift
  Package@swift-6.swift
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Add_binary.p90.json
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Add_string.p90.json
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Iterate_all_values.p90.json
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_binary_values_stored.p90.json
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Iterate_string_values.p90.json
  Performance/Benchmarks/Thresholds/5.8/GRPCSwiftBenchmark.Metadata_Remove_values_for_key.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Add_binary.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Add_string.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Iterate_all_values.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_binary_values_stored.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Iterate_string_values.p90.json
  Performance/Benchmarks/Thresholds/5.9/GRPCSwiftBenchmark.Metadata_Remove_values_for_key.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Add_binary.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Add_string.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Iterate_all_values.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_binary_values_stored.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Iterate_string_values.p90.json
  Performance/Benchmarks/Thresholds/6.0/GRPCSwiftBenchmark.Metadata_Remove_values_for_key.p90.json
  Plugins/GRPCSwiftPlugin/plugin.swift
  Sources/protoc-gen-grpc-swift/main.swift
  Sources/protoc-gen-grpc-swift/options.swift
  scripts/license-check.sh
Labels: semver-patch •

#1957 Test SwiftPM plugin for v2
  .github/workflows/ci.yaml
  Package@swift-6.swift
  scripts/run-plugin-tests.sh
Labels: v2

#1959 Swift 6 lang mode simple fixes
  Package@swift-6.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/ServerTransport.swift
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Connection/ConnectionFactory.swift
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2Core/Internal/ConstantAsyncSequence.swift
  Sources/GRPCHTTP2Core/Internal/DiscardingTaskGroup+CancellableHandle.swift
  Sources/GRPCHTTP2Core/Internal/Timer.swift
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnectionManagementHandler.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/NIOClientBootstrap+SocketAddress.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCInProcessTransport/InProcessServerTransport.swift
  Sources/GRPCInterceptors/OnFinishAsyncSequence.swift
  Sources/interoperability-tests/InteroperabilityTestsExecutable.swift
  Tests/GRPCInterceptorsTests/TracingInterceptorTests.swift
  Tests/GRPCInterceptorsTests/TracingTestsUtilities.swift
  Tests/GRPCProtobufTests/ProtobufCodingTests.swift
Labels: v2

#1958 Fix warnings in SwiftPM plugin
  Plugins/GRPCSwiftPlugin/plugin.swift
Labels: semver-patch •

#1963 Move v1 examples to v1 subdirectory
  Package.swift
  Package@swift-6.swift
  Protos/generate.sh
  Sources/Examples/v1/Echo/Implementation/EchoAsyncProvider.swift
  Sources/Examples/v1/Echo/Implementation/EchoProvider.swift
  Sources/Examples/v1/Echo/Implementation/HPACKHeaders+Prettify.swift
  Sources/Examples/v1/Echo/Implementation/Interceptors.swift
  Sources/Examples/v1/Echo/Model/echo.grpc.swift
  Sources/Examples/v1/Echo/Model/echo.pb.swift
  Sources/Examples/v1/Echo/README.md
  Sources/Examples/v1/Echo/Runtime/Echo.swift
  Sources/Examples/v1/Echo/Runtime/Empty.swift
  Sources/Examples/v1/HelloWorld/Client/HelloWorldClient.swift
  Sources/Examples/v1/HelloWorld/Model/helloworld.grpc.swift
  Sources/Examples/v1/HelloWorld/Model/helloworld.pb.swift
  Sources/Examples/v1/HelloWorld/README.md
  Sources/Examples/v1/HelloWorld/Server/GreeterProvider.swift
  Sources/Examples/v1/HelloWorld/Server/HelloWorldServer.swift
  Sources/Examples/v1/PacketCapture/Empty.swift
  Sources/Examples/v1/PacketCapture/PacketCapture.swift
  Sources/Examples/v1/PacketCapture/README.md
  Sources/Examples/v1/README.md
  Sources/Examples/v1/ReflectionService/Generated/echo.grpc.reflection
  Sources/Examples/v1/ReflectionService/Generated/helloworld.grpc.reflection
  Sources/Examples/v1/ReflectionService/GreeterProvider.swift
  Sources/Examples/v1/ReflectionService/ReflectionServer.swift
  Sources/Examples/v1/RouteGuide/Client/Empty.swift
  Sources/Examples/v1/RouteGuide/Client/RouteGuideClient.swift
  Sources/Examples/v1/RouteGuide/Model/route_guide.grpc.swift
  Sources/Examples/v1/RouteGuide/Model/route_guide.pb.swift
  Sources/Examples/v1/RouteGuide/README.md
  Sources/Examples/v1/RouteGuide/Server/RouteGuideProvider.swift
  Sources/Examples/v1/RouteGuide/Server/RouteGuideServer.swift
  Sources/Examples/v1/RouteGuide/route_guide_db.json
  Sources/GRPCPerformanceTests/Benchmarks/echo.grpc.swift
  Sources/GRPCPerformanceTests/Benchmarks/echo.pb.swift
  Sources/GRPCReflectionService/Documentation.docc/ReflectionServiceTutorial.md
  docs/basic-tutorial.md
  docs/client-without-codegen.md
  docs/interceptors-tutorial.md
  docs/quick-start.md
Labels: semver-noop

#1964 Add a v2 Echo example
  Package@swift-6.swift
  Sources/Examples/v2/Echo/Echo.swift
  Sources/Examples/v2/Echo/Generated/echo.grpc.swift
  Sources/Examples/v2/Echo/Generated/echo.pb.swift
  Sources/Examples/v2/Echo/Subcommands/ClientArguments.swift
  Sources/Examples/v2/Echo/Subcommands/Collect.swift
  Sources/Examples/v2/Echo/Subcommands/Expand.swift
  Sources/Examples/v2/Echo/Subcommands/Get.swift
  Sources/Examples/v2/Echo/Subcommands/Serve.swift
  Sources/Examples/v2/Echo/Subcommands/Update.swift
Labels: v2

#1966 Update test certs
  Sources/GRPCSampleData/GRPCSwiftCertificate.swift
Labels: semver-noop

#1965 Eliminate unnecessary allocations by using single-element writes
  Sources/GRPCCore/Streaming/Internal/RPCWriter+Map.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+MessageToRPCResponsePart.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+Serialize.swift
  Sources/GRPCCore/Streaming/RPCWriter+Closable.swift
  Sources/GRPCCore/Streaming/RPCWriter.swift
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Sources/GRPCHTTP2Core/Client/Connection/Connection.swift
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnection.swift
  Sources/GRPCInterceptors/HookedWriter.swift
  Tests/GRPCCoreTests/Test Utilities/RPCWriter+Utilities.swift
  Tests/GRPCInterceptorsTests/TracingTestsUtilities.swift
Labels: v2

#1967 Enable ExistentialAny for v2
  Package@swift-6.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Configuration/MethodConfig.swift
  Sources/GRPCCore/Configuration/ServiceConfig.swift
  Sources/GRPCCore/RPCError.swift
  Sources/GRPCCore/RuntimeError.swift
  Sources/GRPCCore/Streaming/Internal/BroadcastAsyncSequence.swift
  Sources/GRPCCore/Streaming/Internal/BufferedStream.swift
  Sources/GRPCCore/Streaming/RPCWriter+Closable.swift
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Connection/Connection.swift
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2Core/Client/Connection/RequestQueue.swift
  Sources/GRPCHTTP2Core/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCHTTP2Core/Internal/Timer.swift
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnectionManagementHandler.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/NIOClientBootstrap+SocketAddress.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/InteroperabilityTests/InteroperabilityTestCase.swift
  Sources/performance-worker/WorkerService.swift
  Tests/GRPCProtobufTests/ProtobufCodingTests.swift
Labels: v2

#1969 Avoid unnecessary CoWs in server state machine
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnectionManagementHandler+StateMachine.swift
Labels: v2

#1970 Avoid an error allocation in the server stream handler
  Sources/GRPCHTTP2Core/Server/GRPCServerStreamHandler.swift
Labels: v2

#1972 Fix ':scheme' for posix client
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ClientTransport+Posix.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
Labels: v2

#1973 Update to protobuf 1.27.0
  Package.swift
  Package@swift-6.swift
  Sources/Examples/v1/Echo/Model/echo.pb.swift
  Sources/Examples/v1/HelloWorld/Model/helloworld.pb.swift
  Sources/Examples/v1/RouteGuide/Model/route_guide.pb.swift
  Sources/Examples/v2/Echo/Generated/echo.pb.swift
  Sources/GRPCReflectionService/v1/reflection-v1.pb.swift
  Sources/GRPCReflectionService/v1Alpha/reflection-v1alpha.pb.swift
  Sources/InteroperabilityTests/Generated/empty.pb.swift
  Sources/InteroperabilityTests/Generated/messages.pb.swift
  Sources/Services/Health/Generated/health.pb.swift
  Sources/performance-worker/Generated/grpc_core_stats.pb.swift
  Sources/performance-worker/Generated/grpc_testing_control.pb.swift
  Sources/performance-worker/Generated/grpc_testing_messages.pb.swift
  Sources/performance-worker/Generated/grpc_testing_payloads.pb.swift
  Sources/performance-worker/Generated/grpc_testing_stats.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/code.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/rls.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/rls_config.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/service_config.pb.swift
  Tests/GRPCHTTP2TransportTests/Generated/control.pb.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCTests/Codegen/Normalization/normalization.pb.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Generated/v1/reflection-v1.pb.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/Generated/v1Alpha/reflection-v1alpha.pb.swift
Labels: semver-patch •

#1971 Reuse inbound request headers storage for server streams
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
Labels: v2

#1975 Avoid throwing from the stream state machine
  Sources/GRPCHTTP2Core/Client/GRPCClientStreamHandler.swift
  Sources/GRPCHTTP2Core/Compression/Zlib.swift
  Sources/GRPCHTTP2Core/GRPCMessageFramer.swift
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Sources/GRPCHTTP2Core/Server/GRPCServerStreamHandler.swift
  Tests/GRPCHTTP2CoreTests/Client/GRPCClientStreamHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/GRPCMessageDeframerTests.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: v2

#1976 Use package ACL for v2
  Sources/GRPCCore/Call/Client/CallOptions.swift
  Sources/GRPCCore/Coding/CompressionAlgorithm.swift
  Sources/GRPCCore/Internal/Concurrency Primitives/Lock.swift
  Sources/GRPCCore/Internal/MethodConfigs.swift
  Sources/GRPCCore/Internal/Task+SleepBackport.swift
  Sources/GRPCCore/Streaming/Internal/AsyncStream+MakeStream.swift
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Connection/Connection.swift
  Sources/GRPCHTTP2Core/Client/Connection/ConnectionBackoff.swift
  Sources/GRPCHTTP2Core/Client/Connection/ConnectionFactory.swift
  Sources/GRPCHTTP2Core/Client/Connection/ConnectivityState.swift
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/LoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/LoadBalancerEvent.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/PickFirstLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/RoundRobinLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/Subchannel.swift
  Sources/GRPCHTTP2Core/Client/GRPCClientStreamHandler.swift
  Sources/GRPCHTTP2Core/Compression/CompressionAlgorithm.swift
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Sources/GRPCHTTP2Core/Internal/AsyncStream+MakeStream.swift
  Sources/GRPCHTTP2Core/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCHTTP2Core/Internal/NIOSocketAddress+GRPCSocketAddress.swift
  Sources/GRPCHTTP2Core/Internal/ProcessUniqueID.swift
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnection.swift
  Sources/GRPCHTTP2Core/Server/GRPCServerStreamHandler.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/NIOClientBootstrap+SocketAddress.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInProcessTransport/Internal/AsyncStream+MakeStream.swift
  Sources/InteroperabilityTests/Internal/AsyncStream+MakeStream.swift
  Sources/performance-worker/Internal/AsyncStream+MakeStream.swift
  Tests/GRPCCoreTests/Internal/MethodConfigsTests.swift
  Tests/GRPCCoreTests/Test Utilities/AsyncSequence+Utilities.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/LoadBalancerTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/PickFirstLoadBalancerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/RoundRobinLoadBalancerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/RequestQueueTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/HTTP2Connectors.swift
  Tests/GRPCHTTP2CoreTests/Test Utilities/AsyncStream+MakeStream.swift
  Tests/GRPCInterceptorsTests/TracingTestsUtilities.swift
Labels: v2

#1977 Avoid using NIOSingleStepByteToMessageProcessor
  Sources/GRPCHTTP2Core/GRPCMessageDecoder.swift
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Tests/GRPCHTTP2CoreTests/GRPCMessageDecoderTests.swift
  Tests/GRPCHTTP2CoreTests/GRPCMessageDeframerTests.swift
Labels: v2

#1978 Add underscored products for v2
  Package@swift-6.swift
  Sources/GRPCHTTP2Transport/Exports.swift
  Sources/GRPCHTTP2TransportNIOPosix/Exports.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/Exports.swift
  Sources/GRPCInProcessTransport/Exports.swift
Labels: v2

#1979 Simplfy top-level streamin handling in server transports
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
Labels: v2

#1981 Avoid unnecessary CoWs in client connection handler
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
Labels: v2

#1982 Add `ServiceDescriptor` to GRPCCore
  Sources/GRPCCore/ServiceDescriptor.swift
  Tests/GRPCCoreTests/ServiceDescriptorTests.swift
Labels: v2

#1984 Better closing control over GOAWAYs
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
Labels: v2

#1985 Enable Swift 6 language mode for more modules
  Package@swift-6.swift
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCore/Metadata.swift
  Sources/GRPCCore/Streaming/RPCAsyncSequence.swift
  Sources/GRPCCore/Streaming/RPCWriter.swift
  Sources/GRPCHTTP2Core/Internal/Timer.swift
  Sources/InteroperabilityTests/InteroperabilityTestCase.swift
  Tests/GRPCCodeGenTests/Internal/Renderer/TextBasedRendererTests.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Streaming/Internal/BufferedStreamTests.swift
  Tests/GRPCCoreTests/Test Utilities/Coding+JSON.swift
  Tests/GRPCCoreTests/Test Utilities/RPCWriter+Utilities.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/LoadBalancerTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/NameResolvers.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/TestServer.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Internal/TimerTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
  Tests/GRPCHTTP2TransportTests/Test Utilities/HTTP2StatusCodeServer.swift
Labels: v2

#1986 Avoid allocating a closure for the client rpc executor
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
Labels: v2

#1988 Fix broken symlinks
  FuzzTesting/Package.swift
  FuzzTesting/Sources/EchoImplementation
  FuzzTesting/Sources/EchoModel
Labels: semver-noop

#1989 Remove unnecessary README
  Sources/GRPCHTTP2Core/README.md
Labels: v2

#1990 Use plugin work directory URL
  Plugins/GRPCSwiftPlugin/plugin.swift
Labels: v2

#1991 Save an allocation in BufferedStream
  Sources/GRPCCore/Streaming/Internal/BufferedStream.swift
Labels: v2

#1992 Change visibility of `_makeBackpressuredStream` to `package`
  Sources/GRPCCore/Streaming/Internal/RPCAsyncSequence+Buffered.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
Labels: v2

#1995 Add language mode shim to SwiftPM
  Package@swift-6.swift
Labels: v2

#1996 Shutdown server gracefully in h2 transport tests
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
Labels: v2

#1998 Update test certs
  Sources/GRPCSampleData/GRPCSwiftCertificate.swift
  Sources/GRPCSampleData/bundle.p12
  scripts/make-sample-certs.py
Labels: semver-noop
