Repository grpc/grpc-swift, pull requests merged in 2024-02, with the labels that each got.

#1789 [CodeGenLib] Change location of method descriptor array in generated code
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1790 [CodeGenLib] Fixtures for the generated code
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1792 [ProtobufCodeGen] Use the generated input and output type names
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift
  Sources/protoc-gen-grpc-swift/main.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1794 Use ServiceConfiguration more widely
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/Internal/_MethodConfigurations.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/RetryThrottle.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessTransport.swift
  Tests/GRPCCoreTests/Internal/MethodConfigurationsTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
Labels: v2

#1795 Additional logging for connection pool
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
Labels: semver-patch •

#1797 Generated code fixtures: availability guards and descriptor paths
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1798 Bump version number to 1.21.1
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1799 Log connection age when closing a connection
  Sources/GRPC/GRPCIdleHandler.swift
Labels: semver-patch •

#1802 Update thresholds for main
  Performance/Benchmarks/Thresholds/main/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
Labels: v2

#1801 Combine client and server error into runtime error
  Sources/GRPCCore/ClientError.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/GRPCServer.swift
  Sources/GRPCCore/RuntimeError.swift
  Sources/GRPCCore/ServerError.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/RuntimeErrorTests.swift
Labels: v2

#1804 Fixed .proto file imports handling in ProtobufCodeGenParser
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenerator.swift
  Sources/protoc-gen-grpc-swift/main.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1803 Add a socket address type
  Sources/GRPCHTTP2Core/Client/Resolver/SocketAddress.swift
  Tests/GRPCHTTP2CoreTests/Client/Resolver/SocketAddressTests.swift
  Tests/GRPCHTTP2CoreTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1808 [CodeGenLib] Remove namespace enum generation
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1809 Update README
  README.md
Labels: semver-noop

#1806 Fix namespace name for nested package names
  Sources/GRPCProtobufCodeGen/ProtobufCodeGenParser.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGenParserTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1800 Generate interoperability service and messages
  Package.swift
  Protos/generate.sh
  Protos/tests/interoperability/src/proto/grpc/testing/empty.proto
  Protos/tests/interoperability/src/proto/grpc/testing/empty_service.proto
  Protos/tests/interoperability/src/proto/grpc/testing/messages.proto
  Protos/tests/interoperability/src/proto/grpc/testing/test.proto
  Sources/InteroperabilityTests/Generated/empty.pb.swift
  Sources/InteroperabilityTests/Generated/empty_service.grpc.swift
  Sources/InteroperabilityTests/Generated/empty_service.pb.swift
  Sources/InteroperabilityTests/Generated/messages.pb.swift
  Sources/InteroperabilityTests/Generated/test.grpc.swift
  Sources/InteroperabilityTests/Generated/test.pb.swift
Labels: v2

#1807 Add name resolver protocols and registry
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolverRegistry.swift
  Tests/GRPCHTTP2CoreTests/Client/Resolver/NameResolverRegistryTests.swift
  Tests/GRPCHTTP2CoreTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1813 Add missing availability annotations in tests
  Tests/GRPCHTTP2CoreTests/Client/Resolver/NameResolverRegistryTests.swift
Labels: v2

#1814 Add UnixDomainSocket resolver
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver+UDS.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolverRegistry.swift
  Sources/GRPCHTTP2Core/Internal/ConstantAsyncSequence.swift
  Tests/GRPCHTTP2CoreTests/Client/Resolver/NameResolverRegistryTests.swift
Labels: v2

#1812 [Interop] Implemented the Test Service Provider
  Sources/InteroperabilityTests/TestService.swift
Labels: v2

#1816 Add another missing availability annotation in tests
  Tests/GRPCHTTP2CoreTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1817 [InteropTests] Create test framework
  Sources/InteroperabilityTests/AssertionFailure.swift
Labels: v2

#1815 Add VirtualSocket resolver
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver+VSOCK.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolverRegistry.swift
  Tests/GRPCHTTP2CoreTests/Client/Resolver/NameResolverRegistryTests.swift
Labels: v2
