Repository grpc/grpc-swift, pull requests merged in 2024-06, with the labels that each got.

#1901 Better distinguish between connection drops and regular closes
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Connection/Connection.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/RoundRobinLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/Subchannel.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
Labels: v2

#1903 Add request compression check to interop's TestService
  Sources/InteroperabilityTests/TestService.swift
Labels: v2

#1904 Update to a newer version of NIO HTTP/2
  Package.swift
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Internal/NIOChannelPipeline+GRPC.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/HTTP2Connectors.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/TestServer.swift
Labels: v2

#1905 Use different test error
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
Labels: v2

#1906 Normalise config
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2Core/Client/HTTP2ClientTransport.swift
  Sources/GRPCHTTP2Core/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCHTTP2Core/Server/HTTP2ServerTransport.swift
  Sources/GRPCHTTP2TransportNIOPosix/GRPCHTTP2TransportNIOPosix.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/HTTP2ClientTransportConfigTests.swift
  Tests/GRPCHTTP2CoreTests/Server/HTTP2ServerTransportConfigTests.swift
Labels: v2

#1910 ":path" should have a leading "/"
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Tests/GRPCHTTP2CoreTests/Client/GRPCClientStreamHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: v2

#1908 Better handle errors on client connections
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
Labels: v2

#1911 Pass `CallOptions` through generated stub
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/InteroperabilityTests/Generated/test.grpc.swift
  Sources/performance-worker/Generated/grpc_testing_benchmark_service.grpc.swift
  Sources/performance-worker/Generated/grpc_testing_control.pb.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCoreTests/Configuration/Generated/service_config.pb.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#1909 Add a NIOPosix based client transport
  Package.swift
  Sources/GRPCHTTP2TransportNIOPosix/GRPCHTTP2TransportNIOPosix.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/NIOClientBootstrap+SocketAddress.swift
  Tests/GRPCHTTP2TransportNIOPosixTests/GRPCHTTP2TransportNIOPosixTests.swift
  Tests/GRPCHTTP2TransportNIOTransportServicesTests/GRPCHTTP2TransportNIOTransportServicesTests.swift
Labels: v2

#1915 Start the idle timer when the connection is ready
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
Labels: v2

#1919 Add Swift 6 nightly CI
  .github/workflows/ci.yaml
Labels: semver-noop

#1920 Add editorconfig
  .editorconfig
Labels: semver-noop

#1918 Remove a few retroactive conformance warnings
  Sources/GRPCHTTP2Core/Server/GRPCServerStreamHandler.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCHTTP2CoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: v2

#1917 Require absolute paths
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Tests/GRPCHTTP2CoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: v2

#1921 Add client to v2 interop tests
  Sources/interoperability-tests/InteroperabilityTestsExecutable.swift
Labels: v2

#1926 Update links in documents
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  GOVERNANCE.md
  MAINTAINERS.md
  docs/plugin.md
Labels: semver-noop

#1924 Fix a few server state machine transitions
  Sources/GRPCHTTP2Core/Client/GRPCClientStreamHandler.swift
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Sources/GRPCHTTP2Core/Server/GRPCServerStreamHandler.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Server/GRPCServerStreamHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1925 Add 'cause' to error description if present
  Sources/GRPCCore/RPCError.swift
  Tests/GRPCCoreTests/RPCErrorTests.swift
Labels: v2

#1929 Fix availaibility in RPCError test
  Tests/GRPCCoreTests/RPCErrorTests.swift
Labels: v2

#1928 Add missing v2 interop tests
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Sources/InteroperabilityTests/InteroperabilityTestCase.swift
  Sources/InteroperabilityTests/InteroperabilityTestCases.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
Labels: v2

#1916 Add a service for testing
  Package.swift
  Protos/generate.sh
  Protos/tests/control/control.proto
  Tests/GRPCHTTP2TransportTests/ControlService.swift
  Tests/GRPCHTTP2TransportTests/Generated/control.grpc.swift
  Tests/GRPCHTTP2TransportTests/Generated/control.pb.swift
Labels: v2

#1932 Update platform names in `available` attributes
  Sources/GRPC/PlatformSupport.swift
  Sources/GRPC/Server.swift
  Tests/GRPCTests/FunctionalTests.swift
  Tests/GRPCTests/ZeroLengthWriteTests.swift
Labels: semver-patch •

#1931 Default the server config
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
Labels: v2

#1923 Add pick first to grpc-channel
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
Labels: v2

#1936 Add missing availability
  Tests/GRPCHTTP2TransportTests/ControlService.swift
Labels: v2

#1935 Fix various warnings
  Sources/Examples/Echo/Implementation/Interceptors.swift
  Sources/GRPCInteroperabilityTestsImplementation/GRPCTestingConvenienceMethods.swift
  Sources/GRPCInteroperabilityTestsImplementation/InteroperabilityTestCases.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1.swift
  Sources/GRPCReflectionService/Server/ReflectionServiceV1Alpha.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/EchoHelpers/Interceptors/DelegatingClientInterceptor.swift
  Tests/GRPCTests/GRPCPingHandlerTests.swift
  Tests/GRPCTests/InterceptedRPCCancellationTests.swift
  Tests/GRPCTests/InterceptorsTests.swift
  Tests/GRPCTests/ServerInterceptorPipelineTests.swift
  Tests/GRPCTests/ServerInterceptorTests.swift
Labels: semver-patch •

#1934 Add NIOTS server transport
  Package.swift
  Sources/GRPCHTTP2Core/Internal/NIOSocketAddress+GRPCSocketAddress.swift
  Sources/GRPCHTTP2TransportNIOPosix/NIOClientBootstrap+SocketAddress.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
Labels: v2

#1938 Enable SwiftPM build plugin to use the new code generator plugin
  Plugins/GRPCSwiftPlugin/plugin.swift
Labels: v2

#1940 Enable so_reuseaddr on server transport implementations
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
Labels: v2

#1941 Don't double ack pings
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnectionManagementHandler.swift
  Tests/GRPCHTTP2CoreTests/Server/Connection/ServerConnectionManagementHandlerTests.swift
Labels: v2

#1945 Fix more retroactive warnings
  Sources/Examples/RouteGuide/Client/RouteGuideClient.swift
Labels: semver-noop

#1942 Avoid dropping continuations in grpc channel
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/Subchannel.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
Labels: v2

#1946 Add performance worker CLI
  Package.swift
  Sources/performance-worker/PerformanceWorker.swift
  Sources/performance-worker/main.swift
Labels: v2

#1947 Propagate timeout to server
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+ServerBehavior.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests.swift
Labels: v2

#1951 Manually cleanup unix domain socket path in NIOTS test
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOTransportServicesTests.swift
Labels: semver-noop

#1949 Make Subchannel internal state handling clearer
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/PickFirstLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/RoundRobinLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/Subchannel.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
Labels: v2

#1948 Add HTTP/2 transport integration tests
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
  Tests/GRPCHTTP2TransportTests/Test Utilities/HTTP2StatusCodeServer.swift
  Tests/GRPCHTTP2TransportTests/Test Utilities/XCTest+Utilities.swift
Labels: v2

#1952 Add missing availability
  Tests/GRPCHTTP2TransportTests/Test Utilities/HTTP2StatusCodeServer.swift
Labels: v2
