Repository grpc/grpc-swift, pull requests merged in 2024-09, with the labels that each got.

#2039 Regenerate protos
  Examples/v1/Echo/Model/echo.pb.swift
  Examples/v1/HelloWorld/Model/helloworld.pb.swift
  Examples/v1/RouteGuide/Model/route_guide.pb.swift
  Examples/v2/echo/Generated/echo.pb.swift
  Examples/v2/hello-world/Generated/helloworld.pb.swift
  Sources/InteroperabilityTests/Generated/empty.pb.swift
  Sources/InteroperabilityTests/Generated/empty_service.pb.swift
  Sources/InteroperabilityTests/Generated/test.pb.swift
  Sources/Services/Health/Generated/health.pb.swift
  Sources/performance-worker/Generated/grpc_core_stats.pb.swift
  Sources/performance-worker/Generated/grpc_testing_benchmark_service.pb.swift
  Sources/performance-worker/Generated/grpc_testing_control.pb.swift
  Sources/performance-worker/Generated/grpc_testing_payloads.pb.swift
  Sources/performance-worker/Generated/grpc_testing_stats.pb.swift
  Sources/performance-worker/Generated/grpc_testing_worker_service.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/code.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/rls.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/rls_config.pb.swift
  Tests/GRPCCoreTests/Configuration/Generated/service_config.pb.swift
  Tests/GRPCTests/Codegen/Normalization/normalization.pb.swift
Labels: semver-noop

#2038 Improve error message for missing reflection data
  Sources/GRPCReflectionService/Server/ReflectionService.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceIntegrationTests.swift
  Tests/GRPCTests/GRPCReflectionServiceTests/ReflectionServiceUnitTests.swift
Labels: semver-patch •

#2018 Remove 'BufferedStream'
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Streaming/Internal/BufferedStream.swift
  Sources/GRPCCore/Streaming/Internal/RPCAsyncSequence+Buffered.swift
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/Streaming/Internal/BufferedStreamTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
Labels: v2

#2026 Adopt `Mutex` where possible
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Internal/Concurrency Primitives/Lock.swift
  Sources/GRPCCore/Transport/RetryThrottle.swift
  Sources/GRPCHTTP2Core/Client/Connection/Connection.swift
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/LoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/PickFirstLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/RoundRobinLoadBalancer.swift
  Sources/GRPCHTTP2Core/Client/Connection/LoadBalancers/Subchannel.swift
  Sources/GRPCHTTP2Core/Client/Connection/RequestQueue.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/Services/Health/HealthService.swift
  Tests/GRPCCoreTests/Transport/RetryThrottleTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/LoadBalancerTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/PickFirstLoadBalancerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/RoundRobinLoadBalancerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/RequestQueueTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/TestServer.swift
  Tests/GRPCHTTP2CoreTests/Internal/TimerTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
Labels: v2

#2028 Add the route-guide example for v2
  Examples/v2/route-guide/Generated/route_guide.grpc.swift
  Examples/v2/route-guide/Generated/route_guide.pb.swift
  Examples/v2/route-guide/RouteGuide.swift
  Examples/v2/route-guide/Subcommands/GetFeature.swift
  Examples/v2/route-guide/Subcommands/ListFeatures.swift
  Examples/v2/route-guide/Subcommands/RecordRoute.swift
  Examples/v2/route-guide/Subcommands/RouteChat.swift
  Examples/v2/route-guide/Subcommands/Serve.swift
  Examples/v2/route-guide/route_guide_db.json
  Package@swift-6.swift
  Protos/generate.sh
Labels: v2

#2014 Improve the names of a few commonly used APIs
  Examples/v2/echo/Subcommands/Collect.swift
  Examples/v2/echo/Subcommands/Expand.swift
  Examples/v2/echo/Subcommands/Get.swift
  Examples/v2/echo/Subcommands/Serve.swift
  Examples/v2/echo/Subcommands/Update.swift
  Examples/v2/hello-world/Subcommands/Greet.swift
  Examples/v2/hello-world/Subcommands/Serve.swift
  Examples/v2/route-guide/Subcommands/GetFeature.swift
  Examples/v2/route-guide/Subcommands/ListFeatures.swift
  Examples/v2/route-guide/Subcommands/RecordRoute.swift
  Examples/v2/route-guide/Subcommands/RouteChat.swift
  Examples/v2/route-guide/Subcommands/Serve.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step08-run.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/GRPCServer.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/ServerTransport.swift
  Sources/GRPCHTTP2Core/Client/Connection/GRPCChannel.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessServerTransport.swift
  Sources/interoperability-tests/InteroperabilityTestsExecutable.swift
  Sources/performance-worker/BenchmarkClient.swift
  Sources/performance-worker/PerformanceWorker.swift
  Sources/performance-worker/WorkerService.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOPosixTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOTransportServicesTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
  Tests/InProcessInteroperabilityTests/InProcessInteroperabilityTests.swift
  Tests/Services/HealthTests/HealthTests.swift
Labels: v2

#2044 Make 'finish()' 'async'
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Streaming/RPCWriter+Closable.swift
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+ServerBehavior.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
Labels: v2

#2042 Enable `InternalImportsByDefault` in remaining modules
  Package@swift-6.swift
  Protos/generate.sh
  Sources/InteroperabilityTests/Generated/empty.pb.swift
  Sources/InteroperabilityTests/Generated/messages.pb.swift
  Sources/InteroperabilityTests/InteroperabilityTestCase.swift
  Sources/InteroperabilityTests/InteroperabilityTestCases.swift
  Sources/InteroperabilityTests/TestService.swift
  Sources/Services/Health/Generated/health.pb.swift
  Sources/protoc-gen-grpc-swift/Options.swift
Labels: v2

#2047 Default `UseAccessLevelOnImports` to `false`
  Examples/v2/echo/Generated/echo.grpc.swift
  Examples/v2/echo/Subcommands/Collect.swift
  Examples/v2/hello-world/Generated/helloworld.grpc.swift
  Examples/v2/hello-world/HelloWorld.swift
  Examples/v2/hello-world/Subcommands/Greet.swift
  Examples/v2/hello-world/Subcommands/Serve.swift
  Examples/v2/route-guide/Generated/route_guide.grpc.swift
  Package@swift-6.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec03-step04-gen-grpc.txt
  Sources/performance-worker/BenchmarkClient.swift
  Sources/performance-worker/BenchmarkService.swift
  Sources/performance-worker/Generated/grpc_testing_benchmark_service.grpc.swift
  Sources/performance-worker/Generated/grpc_testing_worker_service.grpc.swift
  Sources/performance-worker/PerformanceWorker.swift
  Sources/performance-worker/RPCStats.swift
  Sources/protoc-gen-grpc-swift/Options.swift
  Tests/GRPCHTTP2TransportTests/ControlService.swift
  Tests/GRPCHTTP2TransportTests/Generated/control.grpc.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOPosixTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOTransportServicesTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
  Tests/GRPCHTTP2TransportTests/Test Utilities/HTTP2StatusCodeServer.swift
  Tests/GRPCHTTP2TransportTests/Test Utilities/XCTest+Utilities.swift
  Tests/GRPCHTTP2TransportTests/XCTestCase+Vsock.swift
Labels: v2

#2036 Add TLS support for NIOPosix H2 client
  Examples/v2/echo/Subcommands/Collect.swift
  Examples/v2/echo/Subcommands/Expand.swift
  Examples/v2/echo/Subcommands/Get.swift
  Examples/v2/echo/Subcommands/Update.swift
  Examples/v2/hello-world/Subcommands/Greet.swift
  Examples/v2/route-guide/Subcommands/GetFeature.swift
  Examples/v2/route-guide/Subcommands/ListFeatures.swift
  Examples/v2/route-guide/Subcommands/RecordRoute.swift
  Examples/v2/route-guide/Subcommands/RouteChat.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOPosix/NIOSSL+GRPC.swift
  Sources/GRPCHTTP2TransportNIOPosix/TLSConfig.swift
  Sources/interoperability-tests/InteroperabilityTestsExecutable.swift
  Sources/performance-worker/WorkerService.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOPosixTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
Labels: v2

#2040 Add support for TLS on H2 NIOTS server transport
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/TLSConfig.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOTransportServicesTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportTests.swift
Labels: v2

#2050 Adopt swift-testing for metadata tests
  Tests/GRPCCoreTests/MetadataTests.swift
Labels: v2

#2046 Enable Swift 6 language mode in GRPCCore
  Package@swift-6.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/Internal/TaskGroup+CancellableTask.swift
  Sources/GRPCCore/Status.swift
  Sources/GRPCCore/Streaming/Internal/GRPCAsyncThrowingStream.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+Map.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+MessageToRPCResponsePart.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+Serialize.swift
  Sources/GRPCCore/Streaming/Internal/UncheckedAsyncIteratorSequence.swift
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInterceptors/HookedWriter.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Test Utilities/RPCWriter+Utilities.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
Labels: v2

#2053 Update plugin bundling script
  scripts/bundle-plugins-for-release.sh
Labels: semver-noop

#2062 Bump version number to 1.23.1
  Sources/GRPC/Version.swift
Labels: semver-patch •

#2061 Rename client interceptor context
  Sources/GRPCCore/Call/Client/ClientContext.swift
  Sources/GRPCCore/Call/Client/ClientInterceptor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCInterceptors/ClientTracingInterceptor.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Client/ClientInterceptors.swift
Labels: v2

#2055 Adopt swift-testing for MethodConfig tests
  Package@swift-6.swift
  Sources/GRPCCore/Configuration/MethodConfig.swift
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.hedging_policy.invalid.max_attempts.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.hedging_policy.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.name.empty.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.name.full.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.name.service_only.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.retry_policy.invalid.backoff_multiplier.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.retry_policy.invalid.initial_backoff.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.retry_policy.invalid.max_attempts.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.retry_policy.invalid.max_backoff.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.retry_policy.invalid.retryable_status_codes.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.retry_policy.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.with_hedging.json
  Tests/GRPCCoreTests/Configuration/Inputs/method_config.with_retries.json
  Tests/GRPCCoreTests/Configuration/MethodConfigCodingTests.swift
  Tests/GRPCCoreTests/Configuration/MethodConfigTests.swift
Labels: v2

#2064 Raise minimum Swift version to 5.9
  .github/workflows/ci.yaml
  Package.swift
  Package@swift-6.swift
  Sources/GRPC/Docs.docc/index.md
Labels: semver-minor ↑

#2059 Propagate context to server RPC handlers
  Examples/v2/echo/Generated/echo.grpc.swift
  Examples/v2/echo/Subcommands/Serve.swift
  Examples/v2/hello-world/Generated/helloworld.grpc.swift
  Examples/v2/hello-world/Subcommands/Serve.swift
  Examples/v2/route-guide/Generated/route_guide.grpc.swift
  Examples/v2/route-guide/Subcommands/Serve.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Call/Server/ServerContext.swift
  Sources/GRPCCore/Call/Server/ServerInterceptor.swift
  Sources/GRPCCore/GRPCServer.swift
  Sources/GRPCCore/Transport/ServerTransport.swift
  Sources/GRPCHTTP2Core/Server/CommonHTTP2ServerTransport.swift
  Sources/GRPCHTTP2TransportNIOPosix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCHTTP2TransportNIOTransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCInProcessTransport/InProcessServerTransport.swift
  Sources/GRPCInterceptors/ServerTracingInterceptor.swift
  Sources/InteroperabilityTests/Generated/test.grpc.swift
  Sources/InteroperabilityTests/TestService.swift
  Sources/Services/Health/Generated/health.grpc.swift
  Sources/Services/Health/HealthService.swift
  Sources/performance-worker/BenchmarkService.swift
  Sources/performance-worker/Generated/grpc_testing_benchmark_service.grpc.swift
  Sources/performance-worker/Generated/grpc_testing_worker_service.grpc.swift
  Sources/performance-worker/WorkerService.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/RPCRouterTests.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Server/ServerInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/Services/BinaryEcho.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCHTTP2TransportTests/ControlService.swift
  Tests/GRPCHTTP2TransportTests/Generated/control.grpc.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOPosixTests.swift
  Tests/GRPCHTTP2TransportTests/HTTP2TransportNIOTransportServicesTests.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
  Tests/GRPCProtobufCodeGenTests/ProtobufCodeGeneratorTests.swift
Labels: v2

#2072 Add an underscore between generated service name and component
  Package.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: ⚠️ semver/major

#2073 Update examples
  Examples/echo/Sources/Generated/echo.grpc.swift
  Examples/echo/Sources/Subcommands/Collect.swift
  Examples/echo/Sources/Subcommands/Expand.swift
  Examples/echo/Sources/Subcommands/Get.swift
  Examples/echo/Sources/Subcommands/Serve.swift
  Examples/echo/Sources/Subcommands/Update.swift
  Examples/hello-world/Sources/Generated/helloworld.grpc.swift
  Examples/hello-world/Sources/Subcommands/Greet.swift
  Examples/hello-world/Sources/Subcommands/Serve.swift
  Examples/route-guide/Sources/Generated/route_guide.grpc.swift
  Examples/route-guide/Sources/Subcommands/GetFeature.swift
  Examples/route-guide/Sources/Subcommands/ListFeatures.swift
  Examples/route-guide/Sources/Subcommands/RecordRoute.swift
  Examples/route-guide/Sources/Subcommands/RouteChat.swift
Labels: semver/none

#2071 Restructure in-process transport
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/GRPCServer.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessServerTransport.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Client.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  Sources/GRPCInProcessTransport/InProcessTransport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+Transport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
Labels: ⚠️ semver/major

#2070 Update tutorials and docs
  .spi.yml
  README.md
  Sources/GRPCCore/Call/Server/ServerInterceptor.swift
  Sources/GRPCCore/Documentation.docc/Articles/Generating-stubs.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Hello-World.tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step01.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step02.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step07-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step08-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec03-step04-gen-grpc.txt
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step02-unimplemented.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step03-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step04-unary.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step05-unary.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step06-server-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step07-server-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step08-client-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step09-bidi-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step10-bidi-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step00-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step01-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step02-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step07-server.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step08-run.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step02-add-run-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step03-create-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step04-run-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step05-stub.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step06-get-feature.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step07-list-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step08-record-route.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step09-route-chat.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Route-Guide.tutorial
  Sources/GRPCInProcessTransport/Documentation.docc/Documentation.md
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
Labels: semver/none
