Repository grpc/grpc-swift, pull requests merged in 2024-11, with the labels that each got.

#2105 Migrate CI to use swiftlang / SwiftNIO common GitHub Actions.
  .github/release.yml
  .github/workflows/ci.yaml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_label.yml
  .github/workflows/soundness.yml
  .license_header_template
  .licenseignore
  .swiftformatignore
  .unacceptablelanguageignore
  CONTRIBUTING.md
  Examples/hello-world/Protos
  Examples/hello-world/Protos/HelloWorld.proto
  IntegrationTests/Benchmarks/Package.swift
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Add_binary.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Add_string.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Iterate_all_values.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_binary_values_stored.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Iterate_string_values.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.0/GRPCSwiftBenchmark.Metadata_Remove_values_for_key.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Add_binary.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Add_string.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Iterate_all_values.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_binary_values_stored.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Iterate_string_values.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-main/GRPCSwiftBenchmark.Metadata_Remove_values_for_key.p90.json
  Package.swift
  Sources/GRPCCore/Configuration/MethodConfig.swift
  Sources/GRPCCore/Configuration/ServiceConfig.swift
  Sources/GRPCCore/Documentation.docc/Development/Design.md
  Sources/GRPCCore/Internal/Base64.swift
  Sources/GRPCCore/Internal/Metadata+GRPC.swift
  Sources/GRPCCore/Status.swift
  Sources/GRPCCore/Timeout.swift
  Sources/GRPCCore/Transport/RetryThrottle.swift
  Sources/GRPCInProcessTransport/Documentation.docc/Documentation.md
  Sources/GRPCInProcessTransport/InProcessTransport+Client.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  dev/build-examples.sh
  dev/check-generated-code.sh
  dev/format.sh
  dev/license-check.sh
  dev/protos/fetch.sh
  dev/protos/generate.sh
  dev/soundness.sh
Labels: semver/minor

#2108 Avoid using vendored lock in BroadcastAsyncSequence
  NOTICES.txt
  Sources/GRPCCore/Internal/Concurrency Primitives/Lock.swift
  Sources/GRPCCore/Streaming/Internal/BroadcastAsyncSequence.swift
Labels: semver/patch

#2106 Add more build settings to test targets
  Package.swift
Labels: semver/none

#2101 Bump min version of swift-nio-extras
  Package.swift
  Package@swift-6.swift
Labels: semver/patch

#2111 Bump version number to 1.24.2
  Sources/GRPC/Version.swift
Labels: semver/patch

#2112 Fix some docs formatting
  Sources/GRPCCore/Documentation.docc/Articles/Generating-stubs.md
  Sources/GRPCCore/Documentation.docc/Development/Benchmarks.md
  Sources/GRPCCore/Documentation.docc/Development/Design.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
Labels: semver/none

#2096 Allow adding `ServerInterceptor`s to specific services and methods
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Call/Server/ServerInterceptor.swift
  Sources/GRPCCore/Call/Server/ServerInterceptorPipelineOperation.swift
  Sources/GRPCCore/GRPCServer.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Server/ServerInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/Services/BinaryEcho.swift
  Tests/GRPCCoreTests/Test Utilities/Services/HelloWorld.swift
Labels: ⚠️ semver/major, v2

#2115 Make structured Swift representation types Sendable
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
Labels: semver/minor

#2114 Don't render just spaces in a line
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
Labels: semver/patch

#2116 Simplify naming of code gen types
  Sources/GRPCCodeGen/CodeGenerationRequest.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TestFunctions.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: ⚠️ semver/major

#2120 Allow metadata to be mutated on server response types
  Sources/GRPCCore/Call/Server/ServerResponse.swift
  Tests/GRPCCoreTests/Call/Server/ServerResponseTests.swift
Labels: semver/minor

#2117 Add structured swift represntation for the generated metadata
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Types.swift
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+MetadataTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwiftTestHelpers.swift
Labels: semver/patch

#2122 Add structured swift represntation for the generated server
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ServerTests.swift
Labels: semver/patch

#2126 Simplify typealias translator
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: semver/patch

#2121 Add 'with-' methods for client and server
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/GRPCServer.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCInProcessTransportTests/ClientServerWithMethods.swift
Labels: semver/minor

#2127 Use ServiceDescriptor within MethodDescriptor
  Sources/GRPCCore/Call/Client/ClientInterceptorPipelineOperation.swift
  Sources/GRPCCore/Call/Server/ServerInterceptorPipelineOperation.swift
  Sources/GRPCCore/Internal/MethodConfigs.swift
  Sources/GRPCCore/MethodDescriptor.swift
  Sources/GRPCCore/ServiceDescriptor.swift
  Tests/GRPCCoreTests/Call/Client/ClientInterceptorPipelineOperationTests.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/RPCRouterTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerInterceptorPipelineOperation.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/Internal/MethodConfigsTests.swift
  Tests/GRPCCoreTests/MethodDescriptorTests.swift
  Tests/GRPCCoreTests/ServiceDescriptorTests.swift
  Tests/GRPCCoreTests/Test Utilities/Services/BinaryEcho.swift
  Tests/GRPCCoreTests/Test Utilities/Services/HelloWorld.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessTransportTests.swift
Labels: ⚠️ semver/major

#2125 Add structured swift represntation for the generated client
  Sources/GRPCCodeGen/Internal/StructuredSwift+Client.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ClientTests.swift
Labels: semver/patch

#2128 Use new structured swift representations
  Sources/GRPCCodeGen/CodeGenerationRequest.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/MetadataTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/TypealiasTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: semver/patch

#2129 Simplify client/server translator tests
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
Labels: semver/none

#2131 Simplify generated code
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Types.swift
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/MetadataTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+MetadataTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: semver/patch

#2133 Add documentation to generated code
  Sources/GRPCCodeGen/Internal/StructuredSwift+Client.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/Docs.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ClientTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+MetadataTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ServerTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/DocsTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: semver/patch

#2134 Add a 'simple' service protocol
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Types.swift
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Sources/GRPCCodeGen/Internal/Translator/Docs.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ServerTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
Labels: semver/patch
