Repository grpc/grpc-swift, pull requests merged in 2024-12, with the labels that each got.

#2136 Add remote peer info to the server context
  Sources/GRPCCore/Call/Server/ServerContext.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Client.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  Sources/GRPCInProcessTransport/InProcessTransport.swift
  Sources/GRPCInProcessTransport/Syscalls.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessTransportTests.swift
Labels: ⚠️ semver/major

#2137 Update parameter labels for GRPCClient
  Sources/GRPCCore/Documentation.docc/Development/Design.md
  Sources/GRPCCore/GRPCClient.swift
Labels: ⚠️ semver/major

#2139 Update examples and tutorials
  Examples/echo/Package.swift
  Examples/echo/Sources/Generated/echo.grpc.swift
  Examples/echo/Sources/Subcommands/Collect.swift
  Examples/echo/Sources/Subcommands/Expand.swift
  Examples/echo/Sources/Subcommands/Get.swift
  Examples/echo/Sources/Subcommands/Serve.swift
  Examples/echo/Sources/Subcommands/Update.swift
  Examples/hello-world/Package.swift
  Examples/hello-world/Sources/Generated/helloworld.grpc.swift
  Examples/hello-world/Sources/Subcommands/Greet.swift
  Examples/hello-world/Sources/Subcommands/Serve.swift
  Examples/route-guide/Package.swift
  Examples/route-guide/Sources/Generated/route_guide.grpc.swift
  Examples/route-guide/Sources/Subcommands/GetFeature.swift
  Examples/route-guide/Sources/Subcommands/ListFeatures.swift
  Examples/route-guide/Sources/Subcommands/RecordRoute.swift
  Examples/route-guide/Sources/Subcommands/RouteChat.swift
  Examples/route-guide/Sources/Subcommands/Serve.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Hello-World.tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step01.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step02.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step03.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step04.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step07-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step08-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step01-struct.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step02-unimplemented.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step03-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step04-unary.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step05-unary.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step06-server-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step07-server-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step08-client-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step09-bidi-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step10-bidi-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step00-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step01-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step02-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step07-server.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step08-run.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step03-create-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step04-run-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step05-stub.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step06-get-feature.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step07-list-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step08-record-route.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step09-route-chat.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Route-Guide.tutorial
Labels: semver/none

#2141 Update generated code
  Examples/echo/Sources/Generated/echo.grpc.swift
  Examples/hello-world/Sources/Generated/helloworld.grpc.swift
  Examples/route-guide/Sources/Generated/route_guide.grpc.swift
Labels: semver/none

#2124 Document support for v1 moving forwards
  README.md
Labels: semver/none

#2142 Enable MemberImportVisibility check on all targets
  Package.swift
  Sources/GRPCCodeGen/CodeGenerationRequest.swift
  Sources/GRPCCodeGen/Internal/Translator/Docs.swift
  Tests/GRPCCoreTests/Configuration/ServiceConfigCodingTests.swift
  Tests/GRPCCoreTests/Test Utilities/Services/HelloWorld.swift
Labels: semver/patch

#2143 Add RPCErrorConvertible
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/RPCError.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/RPCErrorTests.swift
Labels: semver/minor

#2145 Add detailed error example and error article
  Examples/error-details/.gitignore
  Examples/error-details/Package.swift
  Examples/error-details/README.md
  Examples/error-details/Sources/DetailedErrorExample.swift
  Examples/error-details/Sources/Generated/helloworld.grpc.swift
  Examples/error-details/Sources/Generated/helloworld.pb.swift
  Sources/GRPCCore/Documentation.docc/Articles/Errors.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
  dev/protos/generate.sh
Labels: semver/none

#2146 Remove unused Foundation imports
  Sources/GRPCCodeGen/CodeGenerationRequest.swift
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCodeGen/Internal/Translator/Docs.swift
  Sources/GRPCCodeGen/Internal/TypeName.swift
Labels: semver/minor

#2148 Update release.yml
  .github/release.yml
Labels: semver/none

#2149 Add reflection server example
  .licenseignore
  Examples/echo/Sources/Subcommands/EchoService.swift
  Examples/echo/Sources/Subcommands/Serve.swift
  Examples/reflection-server/.gitignore
  Examples/reflection-server/Package.swift
  Examples/reflection-server/README.md
  Examples/reflection-server/Sources/DescriptorSets/echo.pb
  Examples/reflection-server/Sources/Echo/EchoService.swift
  Examples/reflection-server/Sources/Generated/echo.grpc.swift
  Examples/reflection-server/Sources/Generated/echo.pb.swift
  Examples/reflection-server/Sources/ReflectionServer.swift
  dev/protos/generate.sh
Labels: semver/none

#2150 Bump versions
  Examples/echo/Package.swift
  Examples/error-details/Package.swift
  Examples/hello-world/Package.swift
  Examples/reflection-server/Package.swift
  Examples/route-guide/Package.swift
  README.md
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Hello-World.tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step07-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step08-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step00-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step01-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step02-package.swift
Labels: semver/none
