Repository grpc/grpc-swift, pull requests merged in 2024-10, with the labels that each got.

#2076 Improve naming of request/response types
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCore/Call/Client/ClientInterceptor.swift
  Sources/GRPCCore/Call/Client/ClientRequest.swift
  Sources/GRPCCore/Call/Client/ClientResponse.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRequest+Convenience.swift
  Sources/GRPCCore/Call/Client/Internal/ClientResponse+Convenience.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Call/Server/ServerInterceptor.swift
  Sources/GRPCCore/Call/Server/ServerRequest.swift
  Sources/GRPCCore/Call/Server/ServerResponse.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step01.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Resources/hello-world-sec04-step02.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step02-unimplemented.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step03-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step04-unary.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step05-unary.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step06-server-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step07-server-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step08-client-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step09-bidi-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec04-step10-bidi-streaming.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Route-Guide.tutorial
  Sources/GRPCCore/GRPCClient.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCoreTests/Call/Client/ClientRequestTests.swift
  Tests/GRPCCoreTests/Call/Client/ClientResponseTests.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Hedging.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Retries.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerRequestTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerResponseTests.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Client/ClientInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/Call/Server/ServerInterceptors.swift
  Tests/GRPCCoreTests/Test Utilities/Services/BinaryEcho.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
Labels: ⚠️ semver/major

#2077 Update example
  Examples/echo/Sources/Generated/echo.grpc.swift
  Examples/echo/Sources/Subcommands/Serve.swift
  Examples/hello-world/Sources/Generated/helloworld.grpc.swift
  Examples/hello-world/Sources/Subcommands/Serve.swift
  Examples/route-guide/Sources/Generated/route_guide.grpc.swift
  Examples/route-guide/Sources/Subcommands/Serve.swift
Labels: semver/none

#2078 Update examples
  Examples/echo/Package.swift
  Examples/hello-world/Package.swift
  Examples/route-guide/Package.swift
Labels: semver/none

#2079 Add a design doc
  Sources/GRPCCore/Call/Client/ClientRequest.swift
  Sources/GRPCCore/Call/Client/ClientResponse.swift
  Sources/GRPCCore/Call/Server/ServerResponse.swift
  Sources/GRPCCore/Documentation.docc/Development/Design.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
Labels: semver/none

#2084 Add a merge method to Metadata
  Sources/GRPCCore/Metadata.swift
  Tests/GRPCCoreTests/MetadataTests.swift
Labels: semver/minor, v2

#2087 Update branch name in CI
  .github/workflows/ci.yaml
Labels: semver/none

#2086 Ensure file path isn't percent encoded in the plugin
  Plugins/GRPCSwiftPlugin/plugin.swift
Labels: semver/patch

#2091 Remove unbounded variable from formatting script
  dev/format.sh
Labels: semver/patch

#2083 Flatten `RPCError` causes if they're also `RPCError`s with the same code
  Sources/GRPCCore/RPCError.swift
  Tests/GRPCCoreTests/RPCErrorTests.swift
Labels: semver/minor, v2

#2090 Add an RPC cancellation handler
  Sources/GRPCCore/Call/Server/Internal/ServerCancellationManager.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Call/Server/ServerContext+RPCCancellationHandle.swift
  Sources/GRPCCore/Call/Server/ServerContext.swift
  Sources/GRPCCore/Internal/Result+Catching.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerCancellationManagerTests.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerContextTests.swift
  Tests/GRPCInProcessTransportTests/InProcessTransportTests.swift
Labels: ⚠️ semver/major

#2093 Fix decoding of durations in MethodConfig
  Sources/GRPCCore/Configuration/MethodConfig.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerCancellationManagerTests.swift
  Tests/GRPCCoreTests/Configuration/MethodConfigCodingTests.swift
Labels: semver/patch

#2094 Fix route guide tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step03-create-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step04-run-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step05-stub.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step06-get-feature.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step07-list-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step08-record-route.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step09-route-chat.swift
Labels: semver/patch, v2

#2100 Update README to include related repos
  README.md
Labels: semver/none
