Repository grpc/grpc-swift, pull requests merged in 2024-04, with the labels that each got.

#1845 Update formatting script
  Plugins/GRPCSwiftPlugin/plugin.swift
  scripts/format.sh
Labels: semver-noop

#1840 'runServer' implementation for Performance Worker Service
  Sources/performance-worker/WorkerService.swift
Labels: v2

#1850 Add wait-for-ready to method config
  Sources/GRPCCore/Configuration/MethodConfiguration.swift
  Tests/GRPCCoreTests/Configuration/MethodConfigurationCodingTests.swift
Labels: v2

#1848 Allow manually running `release` GH workflow
  .github/workflows/release.yml
Labels: semver-noop

#1852 Add subpool stats
  Sources/GRPC/ConnectionManager.swift
  Sources/GRPC/ConnectionPool/ConnectionManagerID.swift
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectionPool/ConnectionPoolIDs.swift
  Sources/GRPC/ConnectionPool/GRPCChannelPool.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/ConnectionPool/PoolManagerStateMachine.swift
  Sources/GRPC/ConnectionPool/PooledChannel.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolDelegates.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/ConnectionPool/GRPCChannelPoolTests.swift
  Tests/GRPCTests/ConnectionPool/PoolManagerStateMachineTests.swift
Labels: semver-minor ↑

#1853 Remove GRPCLogger
  Sources/GRPC/ConnectionPool/ConnectionPool.swift
  Sources/GRPC/ConnectionPool/PoolManager.swift
  Sources/GRPC/ConnectionPool/PooledChannel.swift
  Sources/GRPC/GRPCClientChannelHandler.swift
  Sources/GRPC/GRPCLogger.swift
  Sources/GRPC/Interceptor/ClientInterceptorContext.swift
  Sources/GRPC/Interceptor/ClientInterceptorPipeline.swift
  Sources/GRPC/Interceptor/ClientTransport.swift
  Sources/GRPC/_EmbeddedThroughput.swift
  Tests/GRPCTests/ClientInterceptorPipelineTests.swift
  Tests/GRPCTests/ConnectionPool/ConnectionPoolTests.swift
  Tests/GRPCTests/ConnectionPool/PoolManagerStateMachineTests.swift
  Tests/GRPCTests/GRPCClientChannelHandlerTests.swift
  Tests/GRPCTests/GRPCLoggerTests.swift
  Tests/GRPCTests/GRPCStatusCodeTests.swift
  Tests/GRPCTests/InterceptedRPCCancellationTests.swift
Labels: semver-patch •

#1851 Performance worker - client stats for runClient RPC
  Sources/performance-worker/BenchmarkClient.swift
  Sources/performance-worker/RPCStats.swift
  Sources/performance-worker/ResourceUsage.swift
  Sources/performance-worker/WorkerService.swift
Labels: v2

#1855 Allow the client connection handler to be closed gracefully
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
Labels: v2

#1854 Add call options
  Sources/GRPCCore/Call/Client/CallOptions.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Configuration/MethodConfiguration.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Hedging.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTests+Retries.swift
  Tests/GRPCCoreTests/Configuration/MethodConfigurationCodingTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
Labels: v2

#1856 Rename a few things
  Sources/GRPCCore/Call/Client/CallOptions.swift
  Sources/GRPCCore/Configuration/MethodConfig.swift
  Sources/GRPCCore/Configuration/ServiceConfig.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/Internal/MethodConfigs.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/RetryThrottle.swift
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver+IPv4.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver+IPv6.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver+UDS.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver+VSOCK.swift
  Sources/GRPCHTTP2Core/Client/Resolver/NameResolver.swift
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnectionManagementHandler+StateMachine.swift
  Sources/GRPCHTTP2Core/Server/Connection/ServerConnectionManagementHandler.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessTransport.swift
  Tests/GRPCCoreTests/Configuration/MethodConfigCodingTests.swift
  Tests/GRPCCoreTests/Configuration/MethodConfigTests.swift
  Tests/GRPCCoreTests/Configuration/ServiceConfigCodingTests.swift
  Tests/GRPCCoreTests/Internal/MethodConfigsTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Resolver/NameResolverRegistryTests.swift
  Tests/GRPCHTTP2CoreTests/Server/Connection/ServerConnectionManagementHandler+StateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Server/Connection/ServerConnectionManagementHandlerTests.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
Labels: v2

#1857 runClient RPC response in performance worker
  Sources/performance-worker/BenchmarkClient.swift
  Sources/performance-worker/RPCStats.swift
  Sources/performance-worker/WorkerService.swift
Labels: v2

#1858 Move CompressionAlgorithm to core
  Sources/GRPCCore/Call/Client/CallOptions.swift
  Sources/GRPCCore/Coding/CompressionAlgorithm.swift
  Sources/GRPCHTTP2Core/Client/GRPCClientStreamHandler.swift
  Sources/GRPCHTTP2Core/Compression/CompressionAlgorithm.swift
  Sources/GRPCHTTP2Core/GRPCStreamStateMachine.swift
  Sources/GRPCHTTP2Core/Server/GRPCServerStreamHandler.swift
  Tests/GRPCCoreTests/Coding/CompressionAlgorithmTests.swift
  Tests/GRPCHTTP2CoreTests/Client/GRPCClientStreamHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCHTTP2CoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: v2

#1860 Add connection backoff
  Sources/GRPCHTTP2Core/Client/Connection/ConnectionBackoff.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionBackoffTests.swift
Labels: v2

#1861 BenchmarkClient RPCs implementation
  Sources/performance-worker/BenchmarkClient.swift
  Sources/performance-worker/Internal/AsyncStream+MakeStream.swift
  Sources/performance-worker/WorkerService.swift
Labels: v2

#1859 Add the HTTP/2 connection
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Connection/Connection.swift
  Sources/GRPCHTTP2Core/Client/Connection/ConnectionFactory.swift
  Sources/GRPCHTTP2Core/Internal/AsyncStream+MakeStream.swift
  Sources/GRPCHTTP2Core/Internal/Result+Catching.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ClientConnectionHandlerTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/HTTP2Connectors.swift
  Tests/GRPCHTTP2CoreTests/Test Utilities/MethodDescriptor+Common.swift
Labels: v2

#1863 Bump version number to 1.23.0
  Sources/GRPC/Version.swift
Labels: semver-patch •

#1866 Add missing availability guards in tests
  Tests/GRPCCoreTests/Call/Client/RetryDelaySequenceTests.swift
  Tests/GRPCCoreTests/TimeoutTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCHTTP2CoreTests/Client/Connection/Utilities/HTTP2Connectors.swift
Labels: semver-noop

#1867 A few helpers to pave the way for subchannel
  Package.swift
  Sources/GRPCHTTP2Core/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCHTTP2Core/Client/Connection/ConnectivityState.swift
  Sources/GRPCHTTP2Core/Internal/ProcessUniqueID.swift
  Tests/GRPCHTTP2CoreTests/Internal/ProcessUniqueIDTests.swift
Labels: v2

#1869 Add `removeAll(where:)` to `Metadata`.
  Sources/GRPCCore/Metadata.swift
  Tests/GRPCCoreTests/MetadataTests.swift
Labels: v2

#1870 Remove lazy connect parameter from client transport
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessClientTransport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
Labels: v2

#1871 Enable `Metadata` to be initializable from a `Sequence` of `Elements`
  Sources/GRPCCore/Metadata.swift
  Tests/GRPCCoreTests/MetadataTests.swift
Labels: v2
