Repository grpc/grpc-swift, pull requests merged in 2025-01, with the labels that each got.

#2151 Make empty generated source files descriptive
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/SourceGenerator.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ClientTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ImportTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+MetadataTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ServerTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwiftTestHelpers.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
Labels: 🔨 semver/patch

#2152 Use a nil Descriptor list for empty proto files
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
Labels: 🔨 semver/patch

#2154 Extend structured swift to support generic structs
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Tests/GRPCCodeGenTests/Internal/Renderer/TextBasedRendererTests.swift
Labels: 🔨 semver/patch

#2158 Add more properties to `ClientContext` and have the `ClientTransport` provide it
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCore/Call/Client/ClientContext.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+HedgingExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+OneShotExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Client.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  Sources/GRPCInProcessTransport/InProcessTransport.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+Transport.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCInProcessTransportTests/InProcessClientTransportTests.swift
  dev/license-check.sh
Labels: ⚠️ semver/major

#2161 Add remote and local peers to `ServerContext`
  Sources/GRPCCore/Call/Client/ClientContext.swift
  Sources/GRPCCore/Call/Client/ClientInterceptor.swift
  Sources/GRPCCore/Call/Server/ServerContext.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCInProcessTransportTests/InProcessTransportTests.swift
Labels: ⚠️ semver/major

#2160 Group DocC docs in the index page
  Sources/GRPCCore/Configuration/MethodConfig.swift
  Sources/GRPCCore/Configuration/ServiceConfig.swift
  Sources/GRPCCore/Documentation.docc/Articles/Error-handling.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
  Sources/GRPCCore/Streaming/RPCWriterProtocol.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/ServerTransport.swift
Labels: 🔨 semver/patch

#2156 Rename 'GRPCClient.run()'
  Sources/GRPCCore/GRPCClient.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCInProcessTransportTests/InProcessTransportTests.swift
Labels: 🆕 semver/minor

#2157 Deduplicate interceptor pipeline operation
  Sources/GRPCCore/Call/Client/ClientInterceptor.swift
  Sources/GRPCCore/Call/ConditionalInterceptor.swift
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Call/Server/ServerInterceptor.swift
  Sources/GRPCCore/Call/Server/ServerInterceptorPipelineOperation.swift
  Sources/GRPCCore/Documentation.docc/Documentation.md
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/GRPCServer.swift
  Tests/GRPCCoreTests/Call/ConditionalInterceptorTests.swift
  Tests/GRPCCoreTests/Call/Server/ServerInterceptorPipelineOperation.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
Labels: ⚠️ semver/major

#2155 Make transport generic over its bag-of-bytes type
  Sources/GRPCCodeGen/Internal/StructuredSwift+Client.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Types.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor+RetryExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Call/Client/Internal/ClientStreamExecutor.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Sources/GRPCCore/Call/Server/RPCRouter.swift
  Sources/GRPCCore/Call/Server/RegistrableRPCService.swift
  Sources/GRPCCore/Coding/Coding.swift
  Sources/GRPCCore/Coding/GRPCContiguousBytes.swift
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/GRPCServer.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+MessageToRPCResponsePart.swift
  Sources/GRPCCore/Streaming/Internal/RPCWriter+Serialize.swift
  Sources/GRPCCore/Transport/ClientTransport.swift
  Sources/GRPCCore/Transport/RPCParts.swift
  Sources/GRPCCore/Transport/ServerTransport.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Client.swift
  Sources/GRPCInProcessTransport/InProcessTransport+Server.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ClientTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ServerTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCoreTests/Call/Client/Internal/ClientRPCExecutorTestSupport/ClientRPCExecutorTestHarness+ServerBehavior.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTestSupport/ServerRPCExecutorTestHarness.swift
  Tests/GRPCCoreTests/Call/Server/Internal/ServerRPCExecutorTests.swift
  Tests/GRPCCoreTests/Call/Server/RPCRouterTests.swift
  Tests/GRPCCoreTests/Coding/CodingTests.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
  Tests/GRPCCoreTests/GRPCServerTests.swift
  Tests/GRPCCoreTests/RPCPartsTests.swift
  Tests/GRPCCoreTests/Test Utilities/Coding+Identity.swift
  Tests/GRPCCoreTests/Test Utilities/Coding+JSON.swift
  Tests/GRPCCoreTests/Test Utilities/Services/BinaryEcho.swift
  Tests/GRPCCoreTests/Test Utilities/Services/HelloWorld.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/AnyTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/StreamCountingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/Transport/ThrowingTransport.swift
  Tests/GRPCCoreTests/Test Utilities/XCTest+Utilities.swift
  Tests/GRPCInProcessTransportTests/InProcessServerTransportTests.swift
  Tests/GRPCInProcessTransportTests/InProcessTransportTests.swift
Labels: ⚠️ semver/major

#2163 Update examples
  Examples/echo/Package.swift
  Examples/echo/Sources/Generated/echo.grpc.swift
  Examples/echo/Sources/Subcommands/Collect.swift
  Examples/echo/Sources/Subcommands/Expand.swift
  Examples/echo/Sources/Subcommands/Get.swift
  Examples/echo/Sources/Subcommands/Update.swift
  Examples/error-details/Package.swift
  Examples/error-details/Sources/DetailedErrorExample.swift
  Examples/error-details/Sources/Generated/helloworld.grpc.swift
  Examples/hello-world/Package.swift
  Examples/hello-world/Sources/Generated/helloworld.grpc.swift
  Examples/hello-world/Sources/Subcommands/Greet.swift
  Examples/reflection-server/Package.swift
  Examples/reflection-server/Sources/Generated/echo.grpc.swift
  Examples/route-guide/Package.swift
  Examples/route-guide/Sources/Generated/route_guide.grpc.swift
  Examples/route-guide/Sources/Subcommands/GetFeature.swift
  Examples/route-guide/Sources/Subcommands/ListFeatures.swift
  Examples/route-guide/Sources/Subcommands/RecordRoute.swift
  Examples/route-guide/Sources/Subcommands/RouteChat.swift
Labels: semver/none

#2165 Update tutorials for beta 3
  README.md
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Hello-World.tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step07-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step08-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step00-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step01-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step02-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step03-create-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step04-run-client.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step05-stub.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step06-get-feature.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step07-list-features.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step08-record-route.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec06-step09-route-chat.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Route-Guide.tutorial
Labels: semver/none

#2166 Remove deprecated API
  Sources/GRPCCore/Call/Server/ServerContext.swift
  Sources/GRPCCore/Documentation.docc/Development/Design.md
  Sources/GRPCCore/GRPCClient.swift
  Sources/GRPCCore/MethodDescriptor.swift
Labels: ⚠️ semver/major

#2172 Update thresholds for nightly-6.1
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Add_binary.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Add_string.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Iterate_all_values.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_binary_values_stored.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Iterate_binary_values_when_only_strings_stored.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Iterate_string_values.p90.json
  IntegrationTests/Benchmarks/Thresholds/nightly-6.1/GRPCSwiftBenchmark.Metadata_Remove_values_for_key.p90.json
Labels: semver/none

#2170 Allow a Status to be created from an HTTP status code
  Sources/GRPCCore/Status.swift
  Tests/GRPCCoreTests/StatusTests.swift
Labels: 🆕 semver/minor

#2171 Use the protoc build plugin in examples
  .github/workflows/pull_request.yml
  Examples/echo/Package.swift
  Examples/echo/Sources/Generated/echo.grpc.swift
  Examples/echo/Sources/Generated/echo.pb.swift
  Examples/echo/Sources/Protos/echo
  Examples/echo/Sources/Protos/grpc-swift-proto-generator-config.json
  Examples/error-details/Package.swift
  Examples/error-details/Sources/Generated/helloworld.grpc.swift
  Examples/error-details/Sources/Generated/helloworld.pb.swift
  Examples/error-details/Sources/Protos/grpc-swift-proto-generator-config.json
  Examples/error-details/Sources/Protos/helloworld.proto
  Examples/hello-world/Package.swift
  Examples/hello-world/Protos/HelloWorld.proto
  Examples/hello-world/Sources/Generated/helloworld.grpc.swift
  Examples/hello-world/Sources/Generated/helloworld.pb.swift
  Examples/hello-world/Sources/Protos/grpc-swift-proto-generator-config.json
  Examples/hello-world/Sources/Protos/helloworld.proto
  Examples/reflection-server/Package.swift
  Examples/reflection-server/Sources/Generated/echo.grpc.swift
  Examples/reflection-server/Sources/Generated/echo.pb.swift
  Examples/reflection-server/Sources/Protos/echo
  Examples/reflection-server/Sources/Protos/grpc-swift-proto-generator-config.json
  Examples/route-guide/Package.swift
  Examples/route-guide/Sources/Generated/route_guide.grpc.swift
  Examples/route-guide/Sources/Generated/route_guide.pb.swift
  Examples/route-guide/Sources/Protos/grpc-swift-proto-generator-config.json
  Examples/route-guide/Sources/Protos/route_guide
  dev/protos/generate.sh
Labels: semver/none

#2169 Simplify code gen lib interface
  Sources/GRPCCodeGen/CodeGenerationRequest.swift
  Sources/GRPCCodeGen/CodeGenerator.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Client.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+Server.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/SpecializedTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/Translator.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ClientTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ImportTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+MetadataTests.swift
  Tests/GRPCCodeGenTests/Internal/StructuredSwift+ServerTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TestFunctions.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: ⚠️ semver/major

#2175 Document what constitutes public API
  Sources/GRPCCore/Documentation.docc/Articles/Public-API.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
Labels: semver/none

#2177 Fix typos/punctuation
  Sources/GRPCCore/Documentation.docc/Articles/Public-API.md
Labels: semver/none

#2179 Update Example READMEs
  Examples/echo/README.md
  Examples/error-details/README.md
  Examples/hello-world/README.md
  Examples/reflection-server/README.md
  Examples/route-guide/README.md
Labels: semver/none

#2176 Document use of the build plugin
  Sources/GRPCCore/Documentation.docc/Articles/Generating-stubs.md
Labels: semver/none

#2181 Update dependencies for rc
  Examples/echo/Package.swift
  Examples/error-details/Package.swift
  Examples/hello-world/Package.swift
  Examples/reflection-server/Package.swift
  Examples/route-guide/Package.swift
  README.md
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Hello-World.tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step07-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step08-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step09-plugin.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step00-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step01-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step02-package.swift
Labels: semver/none

#2186 Fix grpc-swift-protobuf version in hello-world example
  Examples/hello-world/Package.swift
Labels: semver/none

#2187 CI use 6.1 nightlies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#2188 Update dependency requirements and docs
  Examples/echo-metadata/Package.swift
  Examples/echo/Package.swift
  Examples/error-details/Package.swift
  Examples/hello-world/Package.swift
  Examples/reflection-server/Package.swift
  Examples/route-guide/Package.swift
  README.md
  Sources/GRPCCore/Documentation.docc/Documentation.md
  Sources/GRPCCore/Documentation.docc/Tutorials/Hello-World/Hello-World.tutorial
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step07-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step08-description.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec01-step09-plugin.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step00-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step01-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Resources/route-guide-sec05-step02-package.swift
  Sources/GRPCCore/Documentation.docc/Tutorials/Route-Guide/Route-Guide.tutorial
Labels: semver/none

#2167 Add a dev-tool subpackage
  dev/format.sh
  dev/grpc-dev-tool/.gitignore
  dev/grpc-dev-tool/Package.swift
  dev/grpc-dev-tool/Sources/grpc-dev-tool/GRPCDevTool.swift
  dev/grpc-dev-tool/Sources/grpc-dev-tool/Subcommands/GenerateJSON/GRPCCodeGen+Conversions.swift
  dev/grpc-dev-tool/Sources/grpc-dev-tool/Subcommands/GenerateJSON/GRPCDevUtils+GenerateJSON.swift
  dev/grpc-dev-tool/Sources/grpc-dev-tool/Subcommands/GenerateJSON/JSONCodeGenerator.swift
  dev/grpc-dev-tool/Sources/grpc-dev-tool/Subcommands/GenerateJSON/JSONCodeGeneratorRequest.swift
Labels: semver/none

#2185 Fix Metadata's description for prettier printing
  Sources/GRPCCore/Metadata.swift
  Tests/GRPCCoreTests/MetadataTests.swift
Labels: 🔨 semver/patch
