Repository grpc/grpc-swift, pull requests merged in 2025-05, with the labels that each got.

#2229 Fix a few warnings
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Sources/GRPCCore/Call/Client/Internal/ClientRPCExecutor.swift
  Sources/GRPCCore/Call/Server/Internal/ServerRPCExecutor.swift
  Tests/GRPCCoreTests/Call/Server/ServerResponseTests.swift
  Tests/GRPCCoreTests/GRPCClientTests.swift
Labels: 🔨 semver/patch

#2228 Add a new field, transportSpecific to ServerContext
  Sources/GRPCCore/Call/Server/ServerContext.swift
Labels: 🆕 semver/minor

#2231 Drop Swift 5.9
  .github/workflows/ci.yaml
  Package.swift
Labels: 🆕 semver/minor

#2224 fix generated method names
  Sources/protoc-gen-grpc-swift/Generator-Client+AsyncAwait.swift
  Sources/protoc-gen-grpc-swift/Generator-Names.swift
Labels: 🔨 semver/patch

#2232 Generate availability annotations
  Sources/GRPCCodeGen/CodeGenerator.swift
  Sources/GRPCCodeGen/Internal/Renderer/TextBasedRenderer.swift
  Sources/GRPCCodeGen/Internal/StructuredSwift+ServiceMetadata.swift
  Sources/GRPCCodeGen/Internal/StructuredSwiftRepresentation.swift
  Sources/GRPCCodeGen/Internal/Translator/ClientCodeTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/IDLToStructuredSwiftTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/MetadataTranslator.swift
  Sources/GRPCCodeGen/Internal/Translator/ServerCodeTranslator.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ClientCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/IDLToStructuredSwiftTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/ServerCodeTranslatorSnippetBasedTests.swift
  Tests/GRPCCodeGenTests/Internal/Translator/TypealiasTranslatorSnippetBasedTests.swift
Labels: 🆕 semver/minor

#2236 Bump version number to 1.26.0
  Sources/GRPC/Version.swift
Labels: 🔨 semver/patch

#2240 Normalise CI flags
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
